import { Platform, StyleSheet, type ViewStyle } from "react-native";
import { Skoun } from "@/constants/theme";
import { skounShadow } from "@/lib/skounShadow";

const c = Skoun.color;
const t = Skoun.type;
const interactive: ViewStyle =
  Platform.OS === "web"
    ? ({
        cursor: "pointer",
        transitionProperty: "background-color, border-color",
        transitionDuration: "150ms",
      } as ViewStyle)
    : {};

export const matcherStyles = StyleSheet.create({
  overlay: { flex: 1, alignItems: "flex-end", backgroundColor: "transparent" },
  drawer: {
    height: "100%",
    position: "relative",
    backgroundColor: c.surface,
    overflow: "hidden",
    ...skounShadow({ blur: 42, x: -10, y: 0, opacity: 0.1, elevation: 14 }),
  },
  drawerDesktop: { width: 560, borderLeftWidth: 1, borderLeftColor: c.bgWash },
  drawerMobile: { width: "100%" },
  drawerInner: { flex: 1, minHeight: 0, zIndex: 1 },
  header: {
    paddingHorizontal: 18,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "transparent",
  },
  headerMark: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCopy: { flex: 1, gap: 2 },
  title: { fontFamily: t.bodyBold, fontSize: 17, lineHeight: 23, color: c.ink },
  headerSubtitle: {
    fontFamily: t.body,
    fontSize: 11,
    lineHeight: 15,
    color: c.inkMuted,
  },
  progressText: { fontFamily: t.bodyMedium, fontSize: 11, color: c.inkMuted },
  iconButton: {
    ...interactive,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  progressTrack: { height: 2, backgroundColor: c.surfaceMuted },
  menuBody: { flex: 1, minHeight: 0, position: "relative" },
  progressFill: { height: 2, backgroundColor: c.primarySoft },
  threadScroll: { flex: 1, minHeight: 0, zIndex: 1 },
  threadContent: { flexGrow: 1, paddingBottom: 4 },
  conversation: {
    flexGrow: 1,
    paddingLeft: 10,
    paddingRight: 36,
    paddingTop: 20,
    paddingBottom: 18,
    gap: 22,
  },
  welcome: { gap: 6, paddingBottom: 3 },
  greeting: {
    fontFamily: t.bodyBold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.4,
    color: c.ink,
  },
  welcomeCopy: {
    fontFamily: t.body,
    fontSize: 14,
    lineHeight: 20,
    color: c.inkMuted,
  },
  existing: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  exchange: { gap: 12 },
  messageRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  messageRowWithAvatar: { alignItems: "flex-end" },
  botSpacer: { width: 48, height: 48 },
  botAvatarSlot: { width: 48, height: 48, position: "relative" },
  botBubble: {
    flexShrink: 1,
    maxWidth: "86%",
    position: "relative",
    backgroundColor: "#D5DCE6",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 4,
    ...skounShadow({ blur: 14, y: 4, opacity: 0.12, elevation: 3 }),
  },
  messageMark: {
    width: 26,
    height: 26,
    borderRadius: 9,
    marginTop: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.surfaceMuted,
  },
  messageCopy: { flex: 1, gap: 8 },
  pastPrompt: {
    fontFamily: t.bodyMedium,
    fontSize: 15,
    lineHeight: 22,
    color: c.ink,
  },
  currentMessage: { paddingBottom: 2 },
  prompt: {
    fontFamily: t.bodySemi,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.2,
    color: c.ink,
  },
  hint: { fontFamily: t.body, fontSize: 13, lineHeight: 20, color: c.inkMuted },
  answerBubble: {
    ...interactive,
    position: "relative",
    alignSelf: "flex-end",
    maxWidth: "86%",
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: c.primaryMist,
    borderRadius: 18,
    ...skounShadow({ blur: 12, y: 5, opacity: 0.34, elevation: 8 }),
  },
  answerCopy: { flexShrink: 1, gap: 2 },
  answerText: {
    fontFamily: t.bodyMedium,
    fontSize: 14,
    lineHeight: 21,
    color: c.ink,
  },
  answerMeta: {
    fontFamily: t.body,
    fontSize: 10,
    lineHeight: 14,
    color: c.inkMuted,
  },
  readyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingTop: 8,
  },
  readyText: { fontFamily: t.bodyMedium, fontSize: 12, color: c.inkMuted },
  composer: {
    flexShrink: 0,
    marginHorizontal: 16,
    padding: 14,
    borderRadius: 20,
    backgroundColor: c.surfaceMuted,
    gap: 13,
  },
  composerHeading: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "space-between",
  },
  composerLabel: {
    fontFamily: t.bodySemi,
    fontSize: 12,
    lineHeight: 18,
    color: c.ink,
  },
  caption: {
    fontFamily: t.body,
    fontSize: 11,
    lineHeight: 17,
    color: c.inkMuted,
    flexShrink: 1,
  },
  controlsStack: { gap: 8 },
  choicesGrid: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    ...interactive,
    alignSelf: "flex-start",
    maxWidth: "100%",
    minWidth: 0,
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: c.bgWash,
    backgroundColor: c.surface,
  },
  choiceTile: {
    flexBasis: "48%",
    flexGrow: 1,
    flexShrink: 1,
    alignSelf: "stretch",
    minWidth: 0,
    maxWidth: "49%",
    minHeight: 36,
    justifyContent: "flex-start",
    paddingHorizontal: 12,
  },
  chipSelected: { borderColor: c.primary, backgroundColor: "#EEF4FF" },
  chipHover: { borderColor: c.primary },
  chipText: {
    fontFamily: t.bodyMedium,
    fontSize: 12,
    lineHeight: 18,
    color: c.ink,
    flexShrink: 1,
  },
  chipTextSelected: { color: "#245AC0", fontFamily: t.bodySemi },
  importance: {
    alignItems: "flex-end",
    gap: 3,
    position: "relative",
    zIndex: 2,
  },
  importanceLabel: {
    fontFamily: t.body,
    fontSize: 10,
    lineHeight: 13,
    color: c.inkMuted,
    textAlign: "right",
  },
  importanceSegment: {
    flexDirection: "row",
    alignSelf: "flex-end",
    borderRadius: 8,
    padding: 2,
    backgroundColor: c.surfaceMuted,
  },
  importanceHint: {
    fontFamily: t.body,
    fontSize: 10,
    lineHeight: 13,
    color: c.inkMuted,
    textAlign: "right",
  },
  importanceHintFloat: {
    position: "absolute",
    bottom: "100%",
    right: 0,
    marginBottom: 4,
    maxWidth: 176,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: c.surface,
    pointerEvents: "none",
    zIndex: 3,
    ...skounShadow({ blur: 10, y: 4, opacity: 0.12, elevation: 4 }),
    ...(Platform.OS === "web"
      ? ({
          transitionProperty: "opacity",
          transitionDuration: "120ms",
        } as ViewStyle)
      : {}),
  },
  importanceHintHidden: { opacity: 0 },
  segment: {
    flexDirection: "row",
    borderRadius: 8,
    padding: 2,
    backgroundColor: c.surfaceMuted,
  },
  segmentOption: {
    ...interactive,
    minHeight: 26,
    paddingHorizontal: 8,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
  },
  segmentSelected: {
    backgroundColor: c.surface,
    ...skounShadow({ blur: 3, y: 1, opacity: 0.05, elevation: 1 }),
  },
  segmentText: { fontFamily: t.bodyMedium, fontSize: 11, color: c.inkMuted },
  segmentTextSelected: { fontFamily: t.bodySemi, color: c.ink },
  budgetCluster: {
    alignSelf: "center",
    alignItems: "stretch",
    maxWidth: "100%",
    gap: 8,
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
    gap: 12,
  },
  stepperButton: {
    ...interactive,
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: c.bgWash,
    borderRadius: 12,
    backgroundColor: c.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  budgetCopy: { alignItems: "center", gap: 2, minWidth: 0, flexShrink: 1 },
  budgetAmountRow: {
    position: "relative",
    maxWidth: "100%",
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  budgetMeasure: {
    position: "absolute",
    opacity: 0,
    left: 0,
    top: 0,
    pointerEvents: "none",
  },
  budgetPrefix: { textAlign: "left" },
  budgetAmount: {
    fontFamily: t.bodySemi,
    fontSize: 25,
    lineHeight: 32,
    color: c.ink,
    letterSpacing: -0.8,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  budgetAmountInput: {
    textAlign: "left",
    margin: 0,
    paddingVertical: 0,
    paddingHorizontal: 1,
    borderRadius: 0,
    borderBottomWidth: 1.5,
    borderBottomColor: c.border,
    backgroundColor: "transparent",
  },
  budgetAmountInputFocused: { borderBottomColor: c.primary },
  budgetPresets: {
    flexWrap: "nowrap",
    justifyContent: "space-between",
    gap: 8,
  },
  budgetPresetHug: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
  },
  locationPicker: { gap: 8 },
  locationToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  searchField: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 12,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 11,
  },
  searchFieldFocused: { borderColor: c.primary },
  input: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingVertical: 10,
    fontFamily: t.body,
    fontSize: 16,
    lineHeight: 22,
    color: c.ink,
  },
  loading: { paddingVertical: 12 },
  locationResult: {
    ...interactive,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 8,
    minHeight: 44,
    borderRadius: 8,
  },
  locationResultText: {
    flex: 1,
    fontFamily: t.bodyMedium,
    fontSize: 13,
    color: c.ink,
  },
  searchHint: {
    fontFamily: t.body,
    fontSize: 10,
    lineHeight: 15,
    color: c.inkMuted,
    paddingHorizontal: 8,
    paddingTop: 2,
  },
  selectedLocation: {
    ...interactive,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: c.primarySoft,
    backgroundColor: c.surface,
    borderRadius: 12,
  },
  locationCopy: { flex: 1, gap: 3 },
  locationLabel: {
    fontFamily: t.bodySemi,
    fontSize: 14,
    lineHeight: 20,
    color: c.ink,
  },
  footer: {
    flexShrink: 0,
    zIndex: 1,
    paddingHorizontal: 14,
    paddingTop: 10,
    gap: 2,
    backgroundColor: c.surface,
    borderTopWidth: 1,
    borderTopColor: c.bgWash,
  },
  mobileFooter: {
    flexShrink: 1,
    maxHeight: "72%",
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 8,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    ...skounShadow({ blur: 18, y: -4, opacity: 0.06, elevation: 6 }),
  },
  mobileOptionsScroll: { flexGrow: 0, flexShrink: 1 },
  keyboardHeader: { paddingBottom: 4 },
  keyboardHeaderMark: { width: 32, height: 32 },
  keyboardTranscript: { flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
  keyboardThreadContent: { flexGrow: 0, paddingBottom: 0 },
  keyboardConversation: {
    flexGrow: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 0,
  },
  keyboardQuestionTitle: {
    fontFamily: t.bodySemi,
    fontSize: 15,
    lineHeight: 21,
    color: c.ink,
  },
  keyboardFooter: {
    flexGrow: 1,
    maxHeight: "100%",
    paddingTop: 8,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  keyboardOptionsScroll: { flexGrow: 1 },
  keyboardDone: {
    minWidth: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  keyboardDoneText: { fontFamily: t.bodySemi, fontSize: 13, color: c.primary },
  mobileOptionsContent: { gap: 10, paddingBottom: 2 },
  mobileComposer: { gap: 8 },
  mobileComposerHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  mobileComposerTitle: {
    fontFamily: t.bodySemi,
    fontSize: 13,
    lineHeight: 18,
    color: c.ink,
    flexShrink: 1,
  },
  mobileComposerHint: {
    fontFamily: t.body,
    fontSize: 10,
    lineHeight: 15,
    color: c.inkMuted,
    flexShrink: 1,
    textAlign: "right",
  },
  mobileChoice: {
    minHeight: 44,
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    gap: 7,
    backgroundColor: "#F9FAFD",
  },
  mobileChoiceTile: { minHeight: 44 },
  mobileChoiceRow: {
    width: "100%",
    alignSelf: "stretch",
    minHeight: 48,
    paddingHorizontal: 14,
    justifyContent: "flex-start",
  },
  mobileChoiceCompact: {
    flex: 1,
    alignSelf: "stretch",
    paddingHorizontal: 4,
    borderRadius: 10,
  },
  mobileChoiceText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
  },
  mobilePresetText: { flex: 1, fontSize: 11, textAlign: "center" },
  mobileChoiceMark: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.surface,
  },
  mobileChoiceMarkSelected: {
    borderColor: c.primary,
    backgroundColor: c.primary,
  },
  mobileChoiceMarkTile: { borderRadius: 5 },
  mobileOptionRows: { gap: 6 },
  mobileStepper: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "#F3F6FC",
  },
  mobileBudgetAmount: { fontSize: 29, lineHeight: 36 },
  mobileBudgetPresets: {
    flexWrap: "nowrap",
    gap: 8,
    paddingHorizontal: 12,
  },
  mobileLocationSegment: { width: "100%", borderRadius: 12, padding: 3 },
  mobileLocationTab: { flex: 1, minHeight: 44, borderRadius: 9 },
  mobileLocationResult: { borderBottomWidth: 1, borderBottomColor: c.bgWash },
  mobileImportance: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: c.bgWash,
  },
  mobileImportanceCopy: { flex: 1, gap: 2 },
  mobileImportanceLabel: {
    textAlign: "left",
    fontFamily: t.bodyMedium,
    fontSize: 11,
    lineHeight: 15,
    color: c.ink,
  },
  mobileImportanceHint: {
    fontFamily: t.body,
    fontSize: 10,
    lineHeight: 13,
    color: c.inkMuted,
  },
  mobileImportanceOption: { minHeight: 44, paddingHorizontal: 12 },
  mobileNavigation: { flexDirection: "row", alignItems: "center", gap: 8 },
  mobileBack: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.bgWash,
    alignItems: "center",
    justifyContent: "center",
  },
  mobileSkip: {
    minHeight: 44,
    minWidth: 48,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  mobileContinue: { flex: 1, minHeight: 44, paddingVertical: 10, borderRadius: 12 },
  mobileContinueText: { fontFamily: t.bodySemi, fontSize: 14, color: c.surface },
  mobilePartial: {
    minHeight: 32,
    marginTop: -4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    borderRadius: 8,
  },
  mobileFooterHint: {
    fontFamily: t.body,
    fontSize: 11,
    lineHeight: 16,
    color: c.inkMuted,
    textAlign: "center",
    paddingVertical: 6,
  },
  footerBand: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  footerRail: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingTop: 6,
  },
  footerRailStack: {
    flexShrink: 0,
    alignItems: "center",
    gap: 2,
    paddingTop: 4,
  },
  underContinue: {
    flexShrink: 0,
    maxWidth: 176,
    alignItems: "flex-end",
    gap: 4,
    paddingTop: 4,
  },
  underContinueBelow: {
    alignSelf: "flex-end",
    width: 196,
    maxWidth: "70%",
    alignItems: "flex-end",
    gap: 3,
  },
  footerOptions: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    overflow: "hidden",
    gap: 8,
  },
  quietButton: {
    ...interactive,
    minHeight: 28,
    paddingHorizontal: 2,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  quietText: {
    fontFamily: t.bodyMedium,
    fontSize: 12,
    lineHeight: 16,
    color: c.inkMuted,
  },
  backTiny: {
    ...interactive,
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  railPrimary: {
    ...interactive,
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    backgroundColor: c.primary,
  },
  railPrimaryText: {
    fontFamily: t.bodySemi,
    fontSize: 12,
    lineHeight: 16,
    color: c.surface,
  },
  editingLabel: {
    fontFamily: t.bodyMedium,
    fontSize: 11,
    lineHeight: 14,
    color: c.inkMuted,
  },
  footerRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  spacer: { flex: 1 },
  back: {
    ...interactive,
    width: 40,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  textButton: {
    ...interactive,
    minHeight: 44,
    paddingHorizontal: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryText: { fontFamily: t.bodyMedium, fontSize: 13, color: c.inkMuted },
  disabled: { opacity: 0.3 },
  softHover: { backgroundColor: c.surfaceMuted },
  primary: {
    ...interactive,
    minHeight: 46,
    paddingHorizontal: 22,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    borderRadius: 14,
    backgroundColor: c.primary,
  },
  primaryHover: { backgroundColor: "#245FD2" },
  entry: {
    ...interactive,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: c.primary,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    alignSelf: "flex-start",
  },
  entryText: {
    fontFamily: t.bodySemi,
    fontSize: 13,
    lineHeight: 20,
    color: c.surface,
    flexShrink: 1,
  },
  partial: {
    ...interactive,
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    alignSelf: "center",
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  railLink: {
    ...interactive,
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
    alignSelf: "flex-end",
    paddingHorizontal: 2,
    borderRadius: 8,
  },
  partialText: { fontFamily: t.bodyMedium, fontSize: 11, color: c.inkMuted },
  footerHint: {
    minHeight: 36,
    paddingTop: 10,
    textAlign: "center",
    fontFamily: t.body,
    fontSize: 11,
    color: c.inkMuted,
  },
  link: {
    fontFamily: t.bodyMedium,
    fontSize: 13,
    lineHeight: 20,
    color: c.primary,
  },
});
