import { Router } from 'express';
import { z } from 'zod';
import { getPromotionCatalog } from '../../config/promotion-catalog.js';
import { requireAuth } from '../../middleware/auth.js';
import { getCampaignAnalytics } from '../listing-activity/listing-activity.service.js';
import { campaignAction,createPromotion,listPromotions,promotionOptions,readPromotion,promotionNotices } from './promotions.service.js';
const uuid=z.string().uuid();
const createSchema=z.object({listingId:uuid,productId:z.string().min(1),marketKey:z.string().max(200).optional(),mode:z.enum(['start','queue']),autoRenew:z.boolean().default(false),catalogVersion:z.string().min(1),idempotencyKey:z.string().uuid()}).strict();
export const promotionsRouter=Router();
promotionsRouter.get('/catalog',(_req,res)=>res.json({data:getPromotionCatalog()}));
promotionsRouter.use(requireAuth);
promotionsRouter.get('/notifications',async(req,res,next)=>{try{res.json({data:await promotionNotices(req.user!.id)});}catch(e){next(e);}});
promotionsRouter.get('/listings/:id/options',async(req,res,next)=>{try{res.json({data:await promotionOptions(req.user!.id,uuid.parse(req.params.id))});}catch(e){next(e);}});
promotionsRouter.get('/listings/:id',async(req,res,next)=>{try{res.json({data:await listPromotions(req.user!.id,uuid.parse(req.params.id))});}catch(e){next(e);}});
promotionsRouter.post('/',async(req,res,next)=>{try{res.status(201).json({data:await createPromotion(req.user!.id,createSchema.parse(req.body))});}catch(e){next(e);}});
promotionsRouter.get('/:id/analytics',async(req,res,next)=>{try{res.json({data:await getCampaignAnalytics(req.user!.id,uuid.parse(req.params.id))});}catch(e){next(e);}});
promotionsRouter.get('/:id',async(req,res,next)=>{try{res.json({data:await readPromotion(req.user!.id,uuid.parse(req.params.id))});}catch(e){next(e);}});
promotionsRouter.patch('/:id/auto-renew',async(req,res,next)=>{try{const input=z.object({enabled:z.boolean()}).strict().parse(req.body);res.json({data:await campaignAction(req.user!.id,uuid.parse(req.params.id),'auto-renew',input.enabled)});}catch(e){next(e);}});
promotionsRouter.post('/:id/:action',async(req,res,next)=>{try{const action=z.enum(['pause','resume','stop','undo','cancel']).parse(req.params.action);res.json({data:await campaignAction(req.user!.id,uuid.parse(req.params.id),action)});}catch(e){next(e);}});
