import type { GridWindow, GridZone } from "./types";

function win(id: string, start: string, end: string): GridWindow {
  return { id, start, end };
}

export const MOCK_GRID_ZONES: GridZone[] = [
  {
    id: "z-hamra",
    name: "Hamra",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 41,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-hamra-1", "14:00", "20:00")],
    note: "AUB feeder. Evening EDL cut; ishtirak covers the block.",
    updatedAt: "2026-08-24T16:10:00.000Z",
  },
  {
    id: "z-ras-beirut",
    name: "Ras Beirut",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 18,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-ras-1", "13:00", "19:00")],
    note: "Same Hamra feeder family. Afternoon dip only.",
    updatedAt: "2026-08-24T15:40:00.000Z",
  },
  {
    id: "z-achrafieh",
    name: "Achrafieh",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 48,
    generatorDuringCuts: true,
    generatorAmperes: 15,
    cutWindows: [
      win("w-ach-1", "12:00", "16:00"),
      win("w-ach-2", "00:00", "04:00"),
    ],
    note: "Split day/night windows. Sassine side reports 15A.",
    updatedAt: "2026-08-25T09:05:00.000Z",
  },
  {
    id: "z-mar-mikhael",
    name: "Mar Mikhael",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 31,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-mm-1", "17:00", "23:00")],
    note: "Nightlife strip. Generator holds the evening cut.",
    updatedAt: "2026-08-23T21:12:00.000Z",
  },
  {
    id: "z-gemmayzeh",
    name: "Gemmayzeh",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 22,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-gem-1", "17:00", "23:00")],
    note: "Paired with Mar Mikhael on the same schedule.",
    updatedAt: "2026-08-23T21:12:00.000Z",
  },
  {
    id: "z-verdun",
    name: "Verdun",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 15,
    generatorDuringCuts: true,
    generatorAmperes: 20,
    cutWindows: [win("w-ver-1", "18:00", "21:00")],
    note: "Short evening cut. Towers run strong ishtirak.",
    updatedAt: "2026-08-22T11:00:00.000Z",
  },
  {
    id: "z-badaro",
    name: "Badaro",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 14,
    generatorDuringCuts: false,
    generatorAmperes: null,
    cutWindows: [win("w-bad-1", "10:00", "16:00")],
    note: "Daytime EDL gap. Many walk-ups have no shared generator.",
    updatedAt: "2026-08-25T08:20:00.000Z",
  },
  {
    id: "z-jnah",
    name: "Jnah",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 9,
    generatorDuringCuts: true,
    generatorAmperes: 5,
    cutWindows: [
      win("w-jnah-1", "08:00", "14:00"),
      win("w-jnah-2", "20:00", "02:00"),
    ],
    note: "Long dual windows. 5A ishtirak on most streets.",
    updatedAt: "2026-08-21T19:44:00.000Z",
  },
  {
    id: "z-saifi",
    name: "Saifi Village",
    district: "Beirut",
    governorate: "Beirut",
    listingCount: 4,
    generatorDuringCuts: false,
    generatorAmperes: null,
    cutWindows: [],
    note: "Downtown feeder holding 24h EDL this week.",
    updatedAt: "2026-08-25T07:30:00.000Z",
  },
  {
    id: "z-dbayeh",
    name: "Dbayeh",
    district: "Matn",
    governorate: "Mount Lebanon",
    listingCount: 19,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-db-1", "11:00", "19:00")],
    note: "Coastal Matn. Afternoon-to-evening EDL drop.",
    updatedAt: "2026-08-24T12:18:00.000Z",
  },
  {
    id: "z-jounieh",
    name: "Jounieh",
    district: "Keserwan",
    governorate: "Mount Lebanon",
    listingCount: 27,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [
      win("w-jou-1", "09:00", "15:00"),
      win("w-jou-2", "22:00", "02:00"),
    ],
    note: "Keserwan rotation. Overnight window is the painful one.",
    updatedAt: "2026-08-24T18:55:00.000Z",
  },
  {
    id: "z-broummana",
    name: "Broummana",
    district: "Matn",
    governorate: "Mount Lebanon",
    listingCount: 12,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-bro-1", "15:00", "21:00")],
    note: "Hill feeder. Evening cut, generator common in buildings.",
    updatedAt: "2026-08-20T14:02:00.000Z",
  },
  {
    id: "z-tripoli",
    name: "Tripoli",
    district: "Tripoli",
    governorate: "North",
    listingCount: 11,
    generatorDuringCuts: false,
    generatorAmperes: null,
    cutWindows: [
      win("w-tri-1", "06:00", "14:00"),
      win("w-tri-2", "18:00", "02:00"),
    ],
    note: "Severe rotation. Shared generator coverage is patchy.",
    updatedAt: "2026-08-25T10:12:00.000Z",
  },
  {
    id: "z-sidon",
    name: "Sidon",
    district: "Sidon",
    governorate: "South",
    listingCount: 8,
    generatorDuringCuts: true,
    generatorAmperes: 5,
    cutWindows: [win("w-sid-1", "08:00", "20:00")],
    note: "Long daylight cut. 5A ishtirak on most listings.",
    updatedAt: "2026-08-22T17:28:00.000Z",
  },
  {
    id: "z-tyre",
    name: "Tyre",
    district: "Tyre",
    governorate: "South",
    listingCount: 6,
    generatorDuringCuts: false,
    generatorAmperes: null,
    cutWindows: [
      win("w-tyr-1", "07:00", "15:00"),
      win("w-tyr-2", "19:00", "01:00"),
    ],
    note: "South rotation. Dark hours overnight without building gen.",
    updatedAt: "2026-08-25T06:40:00.000Z",
  },
  {
    id: "z-zahle",
    name: "Zahle",
    district: "Zahle",
    governorate: "Bekaa",
    listingCount: 7,
    generatorDuringCuts: true,
    generatorAmperes: 10,
    cutWindows: [win("w-zah-1", "12:00", "22:00")],
    note: "Bekaa afternoon-to-night cut. Generator fills most of it.",
    updatedAt: "2026-08-23T13:33:00.000Z",
  },
];
