import type { AdminReport } from "./types";

function photo(id: string, w = 800): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;
}

const L = {
  foyer: {
    id: "l-03",
    title: "Girls foyer bed near AUB",
    area: "Hamra",
    monthlyRentUsd: 280,
    status: "active" as const,
    coverUrl: photo("photo-1689043528099-2ba014dd7c64"),
    photos: [
      { id: "p-03-1", url: photo("photo-1689043528099-2ba014dd7c64"), caption: "Dorm bunks" },
      { id: "p-03-2", url: photo("photo-1555854877-bab0e564b8d5"), caption: "Corridor" },
    ],
  },
  souk: {
    id: "l-05",
    title: "LAU-ready studio in Old Souk",
    area: "Byblos",
    monthlyRentUsd: 550,
    status: "active" as const,
    coverUrl: photo("photo-1606074280798-2dabb75ce10c"),
    photos: [
      { id: "p-05-1", url: photo("photo-1606074280798-2dabb75ce10c"), caption: "Studio interior" },
      { id: "p-05-2", url: photo("photo-1675279200694-8529c73b1fd0"), caption: "Kitchenette" },
    ],
  },
  fanar: {
    id: "l-09",
    title: "Compact studio near LU Fanar",
    area: "Fanar",
    monthlyRentUsd: 480,
    status: "active" as const,
    coverUrl: photo("photo-1631049307264-da0ec9d70304"),
    photos: [
      { id: "p-09-1", url: photo("photo-1631049307264-da0ec9d70304"), caption: "Studio" },
    ],
  },
  bliss: {
    id: "l-01",
    title: "Bliss Studio near Main Gate",
    area: "Hamra",
    monthlyRentUsd: 650,
    status: "active" as const,
    coverUrl: photo("photo-1522708323590-d24dbb6b0267"),
    photos: [
      { id: "p-01-1", url: photo("photo-1522708323590-d24dbb6b0267"), caption: "Living room facing Bliss" },
    ],
  },
  hamra: {
    id: "l-04",
    title: "Sunny 1BR steps from Hamra Street",
    area: "Hamra",
    monthlyRentUsd: 1100,
    status: "active" as const,
    coverUrl: photo("photo-1560448204-e02f11c3d0e2"),
    photos: [
      { id: "p-04-1", url: photo("photo-1560448204-e02f11c3d0e2"), caption: "Living room" },
    ],
  },
  quiet: {
    id: "l-02",
    title: "Quiet private room off Bliss",
    area: "Hamra",
    monthlyRentUsd: 420,
    status: "active" as const,
    coverUrl: photo("photo-1493809842364-78817add7ffb"),
    photos: [
      { id: "p-02-1", url: photo("photo-1493809842364-78817add7ffb"), caption: "Bedroom" },
    ],
  },
  loft: {
    id: "l-11",
    title: "Catalog loft off Huvelin",
    area: "Achrafieh",
    monthlyRentUsd: 890,
    status: "removed" as const,
    coverUrl: photo("photo-1613575831056-0acd5da8f085"),
    photos: [
      { id: "p-11-1", url: photo("photo-1613575831056-0acd5da8f085"), caption: "Stock living room" },
    ],
  },
  dekwaneh: {
    id: "l-10",
    title: "Affordable room in Dekwaneh",
    area: "Dekwaneh",
    monthlyRentUsd: 320,
    status: "active" as const,
    coverUrl: photo("photo-1595526114035-0d45ed16cfbf"),
    photos: [
      { id: "p-10-1", url: photo("photo-1595526114035-0d45ed16cfbf"), caption: "Room" },
    ],
  },
  huvelin: {
    id: "l-07",
    title: "Huvelin flat near USJ campus",
    area: "Achrafieh",
    monthlyRentUsd: 950,
    status: "archived" as const,
    coverUrl: photo("photo-1613575831056-0acd5da8f085"),
    photos: [
      { id: "p-07-1", url: photo("photo-1613575831056-0acd5da8f085"), caption: "Living room" },
    ],
  },
  sassine: {
    id: "l-08",
    title: "Private room by Sassine & Huvelin",
    area: "Achrafieh",
    monthlyRentUsd: 380,
    status: "active" as const,
    coverUrl: photo("photo-1564078516393-cf04bd966897"),
    photos: [
      { id: "p-08-1", url: photo("photo-1564078516393-cf04bd966897"), caption: "Room" },
    ],
  },
};

const P = {
  hassan: {
    id: "u-06",
    firstName: "Hassan",
    lastName: "Fares",
    email: "hassan.fares@skoun.dev",
    accountStatus: "restricted" as const,
  },
  jad: {
    id: "u-10",
    firstName: "Jad",
    lastName: "Karam",
    email: "jad.karam@hotmail.com",
    accountStatus: "active" as const,
  },
  karim: {
    id: "u-02",
    firstName: "Karim",
    lastName: "Mansour",
    email: "karim.mansour@gmail.com",
    accountStatus: "active" as const,
  },
  fadi: {
    id: "u-12",
    firstName: "Fadi",
    lastName: "Abou Jaoude",
    email: "fadi.aj@gmail.com",
    accountStatus: "active" as const,
  },
  rita: {
    id: "u-07",
    firstName: "Rita",
    lastName: "Bazzi",
    email: "rita.bazzi@gmail.com",
    accountStatus: "active" as const,
  },
  elie: {
    id: "u-04",
    firstName: "Elie",
    lastName: "Saad",
    email: "elie.saad@outlook.com",
    accountStatus: "banned" as const,
  },
};

export const MOCK_REPORTS: AdminReport[] = [
  {
    id: "rp-01",
    reason: "fake",
    queue: "pending",
    createdAt: "2026-08-23T09:12:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    reporter: {
      id: "u-01",
      firstName: "Nour",
      lastName: "Haddad",
      email: "nour.haddad@mail.aub.edu",
      campus: "AUB, Hamra",
    },
    listing: L.foyer,
    poster: P.hassan,
  },
  {
    id: "rp-02",
    reason: "inaccurate_utilities",
    queue: "pending",
    createdAt: "2026-08-24T14:05:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    reporter: {
      id: "u-09",
      firstName: "Layal",
      lastName: "Chami",
      email: "layal.chami@ndu.edu.lb",
      campus: "NDU, Zouk",
    },
    listing: L.souk,
    poster: P.jad,
  },
  {
    id: "rp-03",
    reason: "already_rented",
    queue: "pending",
    createdAt: "2026-08-21T11:18:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    reporter: {
      id: "u-05",
      firstName: "Sara",
      lastName: "Nassar",
      email: "sara.nassar@usj.edu.lb",
      campus: "USJ, Beirut",
    },
    listing: L.fanar,
    poster: P.jad,
  },
  {
    id: "rp-04",
    reason: "fake",
    queue: "pending",
    createdAt: "2026-08-25T08:40:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    reporter: {
      id: "u-11",
      firstName: "Tala",
      lastName: "Hobeika",
      email: "tala.hobeika@usek.edu.lb",
      campus: "USEK, Kaslik",
    },
    listing: L.bliss,
    poster: P.karim,
  },
  {
    id: "rp-05",
    reason: "already_rented",
    queue: "in_review",
    createdAt: "2026-08-22T16:10:00.000Z",
    reviewedAt: "2026-08-25T10:02:00.000Z",
    reviewer: "You",
    note: null,
    reporter: {
      id: "u-03",
      firstName: "Maya",
      lastName: "Khoury",
      email: "maya.khoury@lau.edu",
      campus: "LAU, Byblos",
    },
    listing: L.quiet,
    poster: P.rita,
  },
  {
    id: "rp-06",
    reason: "fake",
    queue: "in_review",
    createdAt: "2026-08-22T16:40:00.000Z",
    reviewedAt: "2026-08-25T11:15:00.000Z",
    reviewer: "Lina A.",
    note: null,
    reporter: {
      id: "u-09",
      firstName: "Layal",
      lastName: "Chami",
      email: "layal.chami@ndu.edu.lb",
      campus: "NDU, Zouk",
    },
    listing: L.foyer,
    poster: P.hassan,
  },
  {
    id: "rp-07",
    reason: "fake",
    queue: "resolved",
    createdAt: "2026-07-28T12:00:00.000Z",
    reviewedAt: "2026-08-01T09:41:00.000Z",
    reviewer: "Rami K.",
    note: "Catalog photos. Listing taken down with poster ban.",
    reporter: {
      id: "u-08",
      firstName: "Omar",
      lastName: "Itani",
      email: "omar.itani@mail.aub.edu",
      campus: "AUB, Hamra",
    },
    listing: L.loft,
    poster: P.elie,
  },
  {
    id: "rp-08",
    reason: "already_rented",
    queue: "resolved",
    createdAt: "2026-08-18T09:22:00.000Z",
    reviewedAt: "2026-08-19T13:05:00.000Z",
    reviewer: "Lina A.",
    note: "Poster confirmed tenant already in. Warning issued.",
    reporter: {
      id: "u-05",
      firstName: "Sara",
      lastName: "Nassar",
      email: "sara.nassar@usj.edu.lb",
      campus: "USJ, Beirut",
    },
    listing: L.dekwaneh,
    poster: P.karim,
  },
  {
    id: "rp-09",
    reason: "inaccurate_utilities",
    queue: "resolved",
    createdAt: "2026-07-30T18:00:00.000Z",
    reviewedAt: "2026-08-01T09:00:00.000Z",
    reviewer: "Rami K.",
    note: "Generator hours did not match copy. Archived on expiry.",
    reporter: {
      id: "u-01",
      firstName: "Nour",
      lastName: "Haddad",
      email: "nour.haddad@mail.aub.edu",
      campus: "AUB, Hamra",
    },
    listing: L.huvelin,
    poster: P.fadi,
  },
  {
    id: "rp-10",
    reason: "fake",
    queue: "dismissed",
    createdAt: "2026-08-16T07:44:00.000Z",
    reviewedAt: "2026-08-17T11:20:00.000Z",
    reviewer: "Lina A.",
    note: "Photos match a prior verified visit. Report closed.",
    reporter: {
      id: "u-11",
      firstName: "Tala",
      lastName: "Hobeika",
      email: "tala.hobeika@usek.edu.lb",
      campus: "USEK, Kaslik",
    },
    listing: L.hamra,
    poster: P.fadi,
  },
  {
    id: "rp-11",
    reason: "already_rented",
    queue: "dismissed",
    createdAt: "2026-08-19T15:30:00.000Z",
    reviewedAt: "2026-08-20T09:10:00.000Z",
    reviewer: "Rami K.",
    note: "Poster still showing the room. Renter had the wrong unit.",
    reporter: {
      id: "u-01",
      firstName: "Nour",
      lastName: "Haddad",
      email: "nour.haddad@mail.aub.edu",
      campus: "AUB, Hamra",
    },
    listing: L.sassine,
    poster: P.rita,
  },
];
