import type { AdminUser } from "./types";

export const MOCK_USERS: AdminUser[] = [
  {
    id: "u-01",
    firstName: "Nour",
    lastName: "Haddad",
    email: "nour.haddad@mail.aub.edu",
    role: "renter",
    accountStatus: "active",
    createdAt: "2026-03-12T09:14:00.000Z",
    campus: "AUB, Hamra",
    reportsFiled: 1,
    reportsAgainst: 0,
    listingCount: 0,
    activeListingCount: 0,
    history: [],
  },
  {
    id: "u-02",
    firstName: "Karim",
    lastName: "Mansour",
    email: "karim.mansour@gmail.com",
    role: "poster",
    accountStatus: "active",
    createdAt: "2025-11-02T16:40:00.000Z",
    campus: "LAU, Beirut",
    reportsFiled: 0,
    reportsAgainst: 1,
    listingCount: 4,
    activeListingCount: 3,
    history: [],
  },
  {
    id: "u-03",
    firstName: "Maya",
    lastName: "Khoury",
    email: "maya.khoury@lau.edu",
    role: "renter",
    accountStatus: "restricted",
    createdAt: "2026-01-19T11:05:00.000Z",
    campus: "LAU, Byblos",
    reportsFiled: 7,
    reportsAgainst: 0,
    listingCount: 0,
    activeListingCount: 0,
    history: [
      {
        id: "h-03-1",
        kind: "warn",
        note: "Cluster of reports with copied text across unrelated listings.",
        at: "2026-07-02T08:22:00.000Z",
        actor: "Lina A.",
      },
      {
        id: "h-03-2",
        kind: "restrict",
        note: "False report pattern continued after warning. Reporting paused.",
        at: "2026-08-11T13:48:00.000Z",
        actor: "Lina A.",
      },
    ],
  },
  {
    id: "u-04",
    firstName: "Elie",
    lastName: "Saad",
    email: "elie.saad@outlook.com",
    role: "poster",
    accountStatus: "banned",
    createdAt: "2025-08-28T07:30:00.000Z",
    campus: "USJ, Beirut",
    reportsFiled: 0,
    reportsAgainst: 9,
    listingCount: 6,
    activeListingCount: 0,
    history: [
      {
        id: "h-04-1",
        kind: "warn",
        note: "Listing photos reused from a furniture catalog.",
        at: "2026-04-18T10:00:00.000Z",
        actor: "Rami K.",
      },
      {
        id: "h-04-2",
        kind: "restrict",
        note: "Asked renters to pay a holding fee off-platform.",
        at: "2026-06-09T15:12:00.000Z",
        actor: "Rami K.",
      },
      {
        id: "h-04-3",
        kind: "ban",
        note: "Repeat off-platform fee request after restrict. Live listings removed.",
        at: "2026-08-01T09:41:00.000Z",
        actor: "Rami K.",
      },
    ],
  },
  {
    id: "u-05",
    firstName: "Sara",
    lastName: "Nassar",
    email: "sara.nassar@usj.edu.lb",
    role: "renter",
    accountStatus: "active",
    createdAt: "2026-05-04T18:21:00.000Z",
    campus: "USJ, Beirut",
    reportsFiled: 0,
    reportsAgainst: 0,
    listingCount: 0,
    activeListingCount: 0,
    history: [],
  },
  {
    id: "u-06",
    firstName: "Hassan",
    lastName: "Fares",
    email: "hassan.fares@skoun.dev",
    role: "poster",
    accountStatus: "restricted",
    createdAt: "2026-02-08T12:00:00.000Z",
    campus: "AUB, Hamra",
    reportsFiled: 0,
    reportsAgainst: 3,
    listingCount: 2,
    activeListingCount: 0,
    history: [
      {
        id: "h-06-1",
        kind: "restrict",
        note: "Gender filter copy violated housing guidelines.",
        at: "2026-08-16T17:05:00.000Z",
        actor: "Lina A.",
      },
    ],
  },
  {
    id: "u-07",
    firstName: "Rita",
    lastName: "Bazzi",
    email: "rita.bazzi@gmail.com",
    role: "poster",
    accountStatus: "active",
    createdAt: "2026-06-22T08:55:00.000Z",
    campus: "Balamand, Koura",
    reportsFiled: 0,
    reportsAgainst: 0,
    listingCount: 1,
    activeListingCount: 1,
    history: [],
  },
  {
    id: "u-08",
    firstName: "Omar",
    lastName: "Itani",
    email: "omar.itani@mail.aub.edu",
    role: "renter",
    accountStatus: "banned",
    createdAt: "2025-12-14T20:10:00.000Z",
    campus: "AUB, Hamra",
    reportsFiled: 11,
    reportsAgainst: 1,
    listingCount: 0,
    activeListingCount: 0,
    history: [
      {
        id: "h-08-1",
        kind: "warn",
        note: "Repeated reports on listings this user never opened.",
        at: "2026-03-01T09:00:00.000Z",
        actor: "Rami K.",
      },
      {
        id: "h-08-2",
        kind: "ban",
        note: "Coordinated false reports against a competing poster.",
        at: "2026-03-21T11:33:00.000Z",
        actor: "Rami K.",
      },
    ],
  },
  {
    id: "u-09",
    firstName: "Layal",
    lastName: "Chami",
    email: "layal.chami@ndu.edu.lb",
    role: "renter",
    accountStatus: "active",
    createdAt: "2026-07-30T14:44:00.000Z",
    campus: "NDU, Zouk",
    reportsFiled: 2,
    reportsAgainst: 0,
    listingCount: 0,
    activeListingCount: 0,
    history: [
      {
        id: "h-09-1",
        kind: "warn",
        note: "Report language was abusive. Report kept, tone flagged.",
        at: "2026-08-20T19:12:00.000Z",
        actor: "Lina A.",
      },
    ],
  },
  {
    id: "u-10",
    firstName: "Jad",
    lastName: "Karam",
    email: "jad.karam@hotmail.com",
    role: "poster",
    accountStatus: "active",
    createdAt: "2026-04-01T06:18:00.000Z",
    campus: "LAU, Beirut",
    reportsFiled: 0,
    reportsAgainst: 2,
    listingCount: 3,
    activeListingCount: 2,
    history: [],
  },
  {
    id: "u-11",
    firstName: "Tala",
    lastName: "Hobeika",
    email: "tala.hobeika@usek.edu.lb",
    role: "renter",
    accountStatus: "active",
    createdAt: "2026-08-03T10:02:00.000Z",
    campus: "USEK, Kaslik",
    reportsFiled: 0,
    reportsAgainst: 0,
    listingCount: 0,
    activeListingCount: 0,
    history: [],
  },
  {
    id: "u-12",
    firstName: "Fadi",
    lastName: "Abou Jaoude",
    email: "fadi.aj@gmail.com",
    role: "poster",
    accountStatus: "active",
    createdAt: "2025-09-17T13:27:00.000Z",
    campus: "USJ, Beirut",
    reportsFiled: 0,
    reportsAgainst: 0,
    listingCount: 8,
    activeListingCount: 5,
    history: [],
  },
];
