import type { AdminInstitution } from "./types";

export const MOCK_INSTITUTIONS: AdminInstitution[] = [
  {
    id: "inst-aub",
    name: "American University of Beirut",
    shortName: "AUB",
    slug: "aub",
    website: "https://www.aub.edu.lb",
    emailDomains: ["aub.edu.lb", "mail.aub.edu"],
    active: true,
    campuses: [
      {
        id: "camp-aub",
        institutionId: "inst-aub",
        name: "Ras Beirut Campus",
        slug: "aub",
        city: "Beirut",
        lng: 35.48212,
        lat: 33.89999,
        isMain: true,
        active: true,
      },
    ],
  },
  {
    id: "inst-lau",
    name: "Lebanese American University",
    shortName: "LAU",
    slug: "lau",
    website: "https://www.lau.edu.lb",
    emailDomains: ["lau.edu.lb"],
    active: true,
    campuses: [
      {
        id: "camp-lau-beirut",
        institutionId: "inst-lau",
        name: "Beirut Campus",
        slug: "lau-beirut",
        city: "Beirut",
        lng: 35.4775,
        lat: 33.89279,
        isMain: true,
        active: true,
      },
      {
        id: "camp-lau-jbeil",
        institutionId: "inst-lau",
        name: "Jbeil Campus",
        slug: "lau-jbeil",
        city: "Jbeil",
        lng: 35.67443,
        lat: 34.1156,
        isMain: false,
        active: true,
      },
    ],
  },
  {
    id: "inst-usj",
    name: "Université Saint-Joseph de Beyrouth",
    shortName: "USJ",
    slug: "usj",
    website: "https://www.usj.edu.lb",
    emailDomains: ["usj.edu.lb"],
    active: true,
    campuses: [
      {
        id: "camp-usj-csm",
        institutionId: "inst-usj",
        name: "Campus des Sciences Médicales",
        slug: "usj-csm",
        city: "Beirut",
        lng: 35.51209,
        lat: 33.88233,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-huvelin",
        institutionId: "inst-usj",
        name: "Campus François Debbané des Sciences Sociales",
        slug: "usj-huvelin",
        city: "Beirut",
        lng: 35.50933,
        lat: 33.88984,
        isMain: true,
        active: true,
      },
      {
        id: "camp-usj-cst",
        institutionId: "inst-usj",
        name: "Campus des Sciences et Technologies",
        slug: "usj-cst",
        city: "Mkalles",
        lng: 35.56415,
        lat: 33.86542,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-csh",
        institutionId: "inst-usj",
        name: "Campus des Sciences Humaines",
        slug: "usj-csh",
        city: "Beirut",
        lng: 35.51162,
        lat: 33.88109,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-cis",
        institutionId: "inst-usj",
        name: "Campus de l'Innovation et du Sport",
        slug: "usj-cis",
        city: "Beirut",
        lng: 35.51449,
        lat: 33.88019,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-corm",
        institutionId: "inst-usj",
        name: "Campus Charles Corm",
        slug: "usj-corm",
        city: "Beirut",
        lng: 35.51399,
        lat: 33.88001,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-cln",
        institutionId: "inst-usj",
        name: "Campus du Liban Nord",
        slug: "usj-cln",
        city: "Ras Maska",
        lng: 35.8069,
        lat: 34.40035,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-cls",
        institutionId: "inst-usj",
        name: "Campus du Liban Sud",
        slug: "usj-cls",
        city: "Saida",
        lng: 35.39665,
        lat: 33.57075,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usj-czb",
        institutionId: "inst-usj",
        name: "Campus de Zahlé et de la Bekaa",
        slug: "usj-czb",
        city: "Zahlé",
        lng: 35.88385,
        lat: 33.85773,
        isMain: false,
        active: true,
      },
    ],
  },
  {
    id: "inst-ndu",
    name: "Notre Dame University–Louaize",
    shortName: "NDU",
    slug: "ndu",
    website: "https://www.ndu.edu.lb",
    emailDomains: ["ndu.edu.lb"],
    active: true,
    campuses: [
      {
        id: "camp-ndu-louaize",
        institutionId: "inst-ndu",
        name: "Zouk Mosbeh Main Campus",
        slug: "ndu-louaize",
        city: "Zouk Mosbeh",
        lng: 35.61371,
        lat: 33.95078,
        isMain: true,
        active: true,
      },
      {
        id: "camp-ndu-nlc",
        institutionId: "inst-ndu",
        name: "North Lebanon Campus",
        slug: "ndu-nlc",
        city: "Barsa",
        lng: 35.82664,
        lat: 34.38274,
        isMain: false,
        active: true,
      },
      {
        id: "camp-ndu-shouf",
        institutionId: "inst-ndu",
        name: "Shouf Campus",
        slug: "ndu-shouf",
        city: "Deir El Qamar",
        lng: 35.5698,
        lat: 33.70329,
        isMain: false,
        active: false,
      },
    ],
  },
  {
    id: "inst-ua",
    name: "Antonine University",
    shortName: "UA",
    slug: "ua",
    website: "https://www.ua.edu.lb",
    emailDomains: ["ua.edu.lb"],
    active: true,
    campuses: [
      {
        id: "camp-ua-hadat",
        institutionId: "inst-ua",
        name: "Hadat–Baabda Main Campus",
        slug: "ua-hadat-baabda",
        city: "Baabda",
        lng: 35.53617,
        lat: 33.83794,
        isMain: true,
        active: true,
      },
      {
        id: "camp-ua-zahle",
        institutionId: "inst-ua",
        name: "Nabi Ayla–Zahle Campus",
        slug: "ua-nabi-ayla",
        city: "Zahle",
        lng: 35.98529,
        lat: 33.86502,
        isMain: false,
        active: true,
      },
      {
        id: "camp-ua-mejdlaya",
        institutionId: "inst-ua",
        name: "Mejdlaya–Zgharta Campus",
        slug: "ua-mejdlaya",
        city: "Zgharta",
        lng: 35.87175,
        lat: 34.4115,
        isMain: false,
        active: true,
      },
    ],
  },
  {
    id: "inst-usek",
    name: "Holy Spirit University of Kaslik",
    shortName: "USEK",
    slug: "usek",
    website: "https://www.usek.edu.lb",
    emailDomains: ["usek.edu.lb"],
    active: true,
    campuses: [
      {
        id: "camp-usek-kaslik",
        institutionId: "inst-usek",
        name: "Kaslik Campus",
        slug: "usek-kaslik",
        city: "Jounieh",
        lng: 35.61866,
        lat: 33.98194,
        isMain: true,
        active: true,
      },
      {
        id: "camp-usek-zahle",
        institutionId: "inst-usek",
        name: "Zahle Campus",
        slug: "usek-zahle",
        city: "Zahle",
        lng: 35.92602,
        lat: 33.84119,
        isMain: false,
        active: true,
      },
      {
        id: "camp-usek-chekka",
        institutionId: "inst-usek",
        name: "Chekka Campus",
        slug: "usek-chekka",
        city: "Chekka",
        lng: 35.73237,
        lat: 34.32429,
        isMain: false,
        active: true,
      },
    ],
  },
  {
    id: "inst-liu",
    name: "Lebanese International University",
    shortName: "LIU",
    slug: "liu",
    website: "https://www.liu.edu.lb",
    emailDomains: ["liu.edu.lb"],
    active: true,
    campuses: [
      {
        id: "camp-liu-beirut",
        institutionId: "inst-liu",
        name: "Beirut Campus",
        slug: "liu-beirut",
        city: "Beirut",
        lng: 35.49536,
        lat: 33.88462,
        isMain: true,
        active: true,
      },
      {
        id: "camp-liu-tripoli",
        institutionId: "inst-liu",
        name: "Tripoli Campus",
        slug: "liu-tripoli",
        city: "Tripoli",
        lng: 35.84273,
        lat: 34.39669,
        isMain: false,
        active: true,
      },
      {
        id: "camp-liu-saida",
        institutionId: "inst-liu",
        name: "Saida Campus",
        slug: "liu-saida",
        city: "Saida",
        lng: 35.37379,
        lat: 33.55366,
        isMain: false,
        active: true,
      },
      {
        id: "camp-liu-bekka",
        institutionId: "inst-liu",
        name: "Bekaa Campus",
        slug: "liu-bekaa",
        city: "Al Khyara",
        lng: 35.85129,
        lat: 33.69292,
        isMain: false,
        active: true,
      },
      {
        id: "camp-liu-tyre",
        institutionId: "inst-liu",
        name: "Tyre Campus",
        slug: "liu-tyre",
        city: "Tyre",
        lng: 35.22923,
        lat: 33.28343,
        isMain: false,
        active: true,
      },
    ],
  },
  {
    id: "inst-global",
    name: "Global University",
    shortName: "GU",
    slug: "global",
    website: "https://www.gu.edu.lb",
    emailDomains: [],
    active: false,
    campuses: [
      {
        id: "camp-global-beirut",
        institutionId: "inst-global",
        name: "Batrakiyeh Campus",
        slug: "global-beirut",
        city: "Beirut",
        lng: 35.49699,
        lat: 33.89042,
        isMain: true,
        active: false,
      },
      {
        id: "camp-global-doha",
        institutionId: "inst-global",
        name: "Doha Campus",
        slug: "global-doha",
        city: "Doha",
        lng: 35.48816,
        lat: 33.76081,
        isMain: false,
        active: false,
      },
    ],
  },
];
