import type { LedgerTx, LedgerUser } from "./types";

const U = {
  karim: {
    id: "u-02",
    firstName: "Karim",
    lastName: "Mansour",
    email: "karim.mansour@gmail.com",
  },
  rita: {
    id: "u-07",
    firstName: "Rita",
    lastName: "Bazzi",
    email: "rita.bazzi@gmail.com",
  },
  hassan: {
    id: "u-06",
    firstName: "Hassan",
    lastName: "Fares",
    email: "hassan.fares@skoun.dev",
  },
  jad: {
    id: "u-10",
    firstName: "Jad",
    lastName: "Karam",
    email: "jad.karam@hotmail.com",
  },
  fadi: {
    id: "u-12",
    firstName: "Fadi",
    lastName: "Abou Jaoude",
    email: "fadi.aj@gmail.com",
  },
  elie: {
    id: "u-04",
    firstName: "Elie",
    lastName: "Saad",
    email: "elie.saad@outlook.com",
  },
} satisfies Record<string, LedgerUser>;

export const GRANT_TARGETS: LedgerUser[] = [
  U.karim,
  U.rita,
  U.hassan,
  U.jad,
  U.fadi,
  U.elie,
];

export const MOCK_TRANSACTIONS: LedgerTx[] = [
  {
    id: "tx-01",
    referenceId: "SK-8F2A19",
    kind: "purchased",
    status: "pending",
    channel: "whish",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: "2026-08-25T09:14:00.000Z",
    note: null,
    user: U.karim,
  },
  {
    id: "tx-02",
    referenceId: "SK-3C91BE",
    kind: "purchased",
    status: "pending",
    channel: "omt",
    bundleType: "starter",
    amountUsdCents: 1000,
    postCredits: 1,
    boostCredits: 0,
    createdAt: "2026-08-24T18:02:00.000Z",
    note: null,
    user: U.rita,
  },
  {
    id: "tx-03",
    referenceId: "SK-AA12D0",
    kind: "purchased",
    status: "pending",
    channel: "whish",
    bundleType: "boost_pack",
    amountUsdCents: 1000,
    postCredits: 0,
    boostCredits: 3,
    createdAt: "2026-08-24T11:40:00.000Z",
    note: null,
    user: U.jad,
  },
  {
    id: "tx-04",
    referenceId: "SK-77E401",
    kind: "purchased",
    status: "success",
    channel: "whish",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: "2026-08-20T08:22:00.000Z",
    note: "Whish confirmed.",
    user: U.fadi,
  },
  {
    id: "tx-05",
    referenceId: "SK-B90F33",
    kind: "purchased",
    status: "success",
    channel: "omt",
    bundleType: "starter",
    amountUsdCents: 1000,
    postCredits: 1,
    boostCredits: 0,
    createdAt: "2026-08-18T16:05:00.000Z",
    note: "OMT slip matched.",
    user: U.karim,
  },
  {
    id: "tx-06",
    referenceId: "SK-11C8A2",
    kind: "purchased",
    status: "success",
    channel: "whish",
    bundleType: "boost_pack",
    amountUsdCents: 1000,
    postCredits: 0,
    boostCredits: 3,
    createdAt: "2026-08-12T13:48:00.000Z",
    note: null,
    user: U.rita,
  },
  {
    id: "tx-07",
    referenceId: "SK-D4E018",
    kind: "purchased",
    status: "failed",
    channel: "omt",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: "2026-08-10T10:11:00.000Z",
    note: "Reference expired. No slip received.",
    user: U.hassan,
  },
  {
    id: "tx-08",
    referenceId: "SK-9A2F70",
    kind: "purchased",
    status: "failed",
    channel: "whish",
    bundleType: "starter",
    amountUsdCents: 1000,
    postCredits: 1,
    boostCredits: 0,
    createdAt: "2026-08-08T19:30:00.000Z",
    note: "Wrong amount transferred.",
    user: U.jad,
  },
  {
    id: "tx-09",
    referenceId: "GR-01LINA",
    kind: "granted",
    status: "success",
    channel: "staff",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: 1,
    boostCredits: 0,
    createdAt: "2026-08-21T12:00:00.000Z",
    note: "Compensation for a listing taken down in error.",
    user: U.rita,
  },
  {
    id: "tx-10",
    referenceId: "GR-02RAMI",
    kind: "granted",
    status: "success",
    channel: "staff",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: 2,
    boostCredits: 1,
    createdAt: "2026-08-15T09:41:00.000Z",
    note: "Campus ambassador promo — AUB week.",
    user: U.karim,
  },
  {
    id: "tx-11",
    referenceId: "GR-03LINA",
    kind: "granted",
    status: "success",
    channel: "staff",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: 0,
    boostCredits: 2,
    createdAt: "2026-08-05T14:18:00.000Z",
    note: "Boost credits for USJ launch weekend.",
    user: U.fadi,
  },
  {
    id: "tx-12",
    referenceId: "SK-EE4411",
    kind: "purchased",
    status: "success",
    channel: "omt",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: "2026-07-28T07:55:00.000Z",
    note: null,
    user: U.elie,
  },
];
