import { ANCHOR_ISO, type LedgerTx, type LedgerUser } from "./types";

const U = {
  karim: {
    id: "u-02",
    firstName: "Karim",
    lastName: "Mansour",
    email: "karim.mansour@gmail.com",
  },
  rita: {
    id: "u-07",
    firstName: "Rita",
    lastName: "Bazzi",
    email: "rita.bazzi@gmail.com",
  },
  hassan: {
    id: "u-06",
    firstName: "Hassan",
    lastName: "Fares",
    email: "hassan.fares@skoun.dev",
  },
  jad: {
    id: "u-10",
    firstName: "Jad",
    lastName: "Karam",
    email: "jad.karam@hotmail.com",
  },
  fadi: {
    id: "u-12",
    firstName: "Fadi",
    lastName: "Abou Jaoude",
    email: "fadi.aj@gmail.com",
  },
  elie: {
    id: "u-04",
    firstName: "Elie",
    lastName: "Saad",
    email: "elie.saad@outlook.com",
  },
} satisfies Record<string, LedgerUser>;

export const GRANT_TARGETS: LedgerUser[] = [
  U.karim,
  U.rita,
  U.hassan,
  U.jad,
  U.fadi,
  U.elie,
];

const hours = (n: number) =>
  new Date(new Date(ANCHOR_ISO).getTime() - n * 60 * 60 * 1000).toISOString();

export const MOCK_TRANSACTIONS: LedgerTx[] = [
  {
    id: "tx-01",
    referenceId: "SK-8F2A19",
    kind: "purchase",
    status: "completed",
    channel: "whish",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: hours(8),
    note: "Demo gateway auto-settle.",
    user: U.karim,
    listingId: null,
  },
  {
    id: "tx-02",
    referenceId: "SK-SP-L01",
    kind: "spend",
    status: "completed",
    channel: "listing",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: -1,
    boostCredits: 0,
    createdAt: hours(6),
    note: "Extra live listing.",
    user: U.karim,
    listingId: "l-01",
  },
  {
    id: "tx-03",
    referenceId: "SK-3C91BE",
    kind: "purchase",
    status: "completed",
    channel: "omt",
    bundleType: "starter",
    amountUsdCents: 1000,
    postCredits: 1,
    boostCredits: 0,
    createdAt: hours(28),
    note: "Demo gateway auto-settle.",
    user: U.rita,
    listingId: null,
  },
  {
    id: "tx-04",
    referenceId: "SK-SP-L02",
    kind: "spend",
    status: "completed",
    channel: "listing",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: -1,
    boostCredits: 0,
    createdAt: hours(26),
    note: "Extra live listing.",
    user: U.rita,
    listingId: "l-02",
  },
  {
    id: "tx-05",
    referenceId: "SK-AA12D0",
    kind: "purchase",
    status: "completed",
    channel: "whish",
    bundleType: "boost_pack",
    amountUsdCents: 1000,
    postCredits: 0,
    boostCredits: 3,
    createdAt: hours(40),
    note: "Demo gateway auto-settle.",
    user: U.jad,
    listingId: null,
  },
  {
    id: "tx-06",
    referenceId: "SK-77E401",
    kind: "purchase",
    status: "completed",
    channel: "whish",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: hours(120),
    note: "Demo gateway auto-settle.",
    user: U.fadi,
    listingId: null,
  },
  {
    id: "tx-07",
    referenceId: "SK-RF-77E4",
    kind: "refund",
    status: "refunded",
    channel: "whish",
    bundleType: "bundle_5",
    amountUsdCents: -1500,
    postCredits: -5,
    boostCredits: 0,
    createdAt: hours(96),
    note: "Duplicate charge. Credits clawed back.",
    user: U.fadi,
    listingId: null,
  },
  {
    id: "tx-08",
    referenceId: "SK-B90F33",
    kind: "purchase",
    status: "disputed",
    channel: "omt",
    bundleType: "starter",
    amountUsdCents: 1000,
    postCredits: 1,
    boostCredits: 0,
    createdAt: hours(160),
    note: "Poster flagged a double debit. Hold until bank reply.",
    user: U.karim,
    listingId: null,
  },
  {
    id: "tx-09",
    referenceId: "SK-D4E018",
    kind: "purchase",
    status: "failed",
    channel: "omt",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: hours(360),
    note: "Gateway timeout. No credits moved.",
    user: U.hassan,
    listingId: null,
  },
  {
    id: "tx-10",
    referenceId: "GR-01LINA",
    kind: "grant",
    status: "completed",
    channel: "staff",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: 1,
    boostCredits: 0,
    createdAt: hours(90),
    note: "Compensation for a listing taken down in error.",
    user: U.rita,
    listingId: null,
  },
  {
    id: "tx-11",
    referenceId: "AJ-02RAMI",
    kind: "adjustment",
    status: "completed",
    channel: "staff",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: -1,
    boostCredits: 0,
    createdAt: hours(72),
    note: "Claw back unused promo post credit.",
    user: U.karim,
    listingId: null,
  },
  {
    id: "tx-12",
    referenceId: "SK-EE4411",
    kind: "purchase",
    status: "completed",
    channel: "omt",
    bundleType: "bundle_5",
    amountUsdCents: 1500,
    postCredits: 5,
    boostCredits: 0,
    createdAt: hours(680),
    note: "Demo gateway auto-settle.",
    user: U.elie,
    listingId: null,
  },
  {
    id: "tx-13",
    referenceId: "SK-SP-L04",
    kind: "spend",
    status: "completed",
    channel: "listing",
    bundleType: "custom",
    amountUsdCents: 0,
    postCredits: -1,
    boostCredits: 0,
    createdAt: hours(50),
    note: "Extra live listing.",
    user: U.fadi,
    listingId: "l-04",
  },
];
