import type { CreditPackage, PricingEngine, PromoCode } from "./types";

export const DEFAULT_ENGINE: PricingEngine = {
  postCreditUsd: 10,
  boostCreditUsd: 3.5,
  marketLbp: 89500,
  officialLbp: 89500,
  bufferPct: 3,
  roundTo: 50000,
};

/** Matches live BUNDLE_CATALOG / CREDIT_BUNDLES. bonusPct is a future catalog field. */
export const MOCK_PACKAGES: CreditPackage[] = [
  {
    id: "starter",
    name: "Starter",
    tagline: "1 post credit — 30 days live",
    basePostCredits: 1,
    baseBoostCredits: 0,
    bonusPct: 0,
    priceUsd: 10,
    active: true,
  },
  {
    id: "bundle_5",
    name: "$15 for 5",
    tagline: "5 post credits",
    basePostCredits: 5,
    baseBoostCredits: 0,
    bonusPct: 0,
    priceUsd: 15,
    active: true,
    featured: true,
  },
  {
    id: "boost_pack",
    name: "Boost Pack",
    tagline: "3 boost credits — 7 days pin each",
    basePostCredits: 0,
    baseBoostCredits: 3,
    bonusPct: 0,
    priceUsd: 10,
    active: true,
  },
];

export const MOCK_PROMOS: PromoCode[] = [
  {
    id: "promo-1",
    code: "AUBWEEK26",
    name: "AUB orientation week",
    kind: "percent",
    value: 25,
    usageLimit: 200,
    usageCount: 86,
    startsAt: "2026-08-18",
    expiresAt: "2026-09-12",
    status: "active",
    appliesTo: "starter",
  },
  {
    id: "promo-2",
    code: "BULKFALL",
    name: "Fall landlord bulk",
    kind: "percent",
    value: 15,
    usageLimit: 80,
    usageCount: 31,
    startsAt: "2026-08-01",
    expiresAt: "2026-10-31",
    status: "active",
    appliesTo: "bundle_5",
  },
  {
    id: "promo-3",
    code: "BROKER10",
    name: "Q3 broker desk",
    kind: "amount",
    value: 10,
    usageLimit: 40,
    usageCount: 12,
    startsAt: "2026-08-01",
    expiresAt: "2026-09-30",
    status: "paused",
    appliesTo: "boost_pack",
  },
  {
    id: "promo-4",
    code: "RAMADAN",
    name: "Ramadan boost nights",
    kind: "amount",
    value: 3,
    usageLimit: 150,
    usageCount: 0,
    startsAt: "2027-02-18",
    expiresAt: "2027-03-20",
    status: "scheduled",
    appliesTo: "all",
  },
  {
    id: "promo-5",
    code: "LAUOPEN",
    name: "LAU open house",
    kind: "percent",
    value: 20,
    usageLimit: 120,
    usageCount: 120,
    startsAt: "2026-06-01",
    expiresAt: "2026-07-15",
    status: "expired",
    appliesTo: "bundle_5",
  },
  {
    id: "promo-6",
    code: "WELCOME1",
    name: "First paid listing",
    kind: "percent",
    value: 10,
    usageLimit: 500,
    usageCount: 214,
    startsAt: "2026-01-01",
    expiresAt: "2026-12-31",
    status: "active",
    appliesTo: "all",
  },
];
