import type { CreditPackage, PricingEngine, PromoCode } from "./types";

export const DEFAULT_ENGINE: PricingEngine = {
  postCreditUsd: 10,
  boostCreditUsd: 3.5,
  marketLbp: 89500,
  officialLbp: 89500,
  bufferPct: 3,
  roundTo: 50000,
};

export const MOCK_PACKAGES: CreditPackage[] = [
  {
    id: "basic",
    catalogType: "starter",
    name: "Basic",
    tagline: "One live listing, 30 days. First paid post after the free slot.",
    basePostCredits: 1,
    baseBoostCredits: 0,
    bonusPct: 0,
    priceUsd: 10,
  },
  {
    id: "bulk",
    catalogType: "bundle_5",
    name: "Bulk",
    tagline: "Five post credits. House rate for landlords with a few units.",
    basePostCredits: 5,
    baseBoostCredits: 0,
    bonusPct: 0,
    priceUsd: 15,
    featured: true,
  },
  {
    id: "pro",
    catalogType: "boost_pack",
    name: "Pro Manager",
    tagline: "Posts plus pin boosts for brokers running a street of stock.",
    basePostCredits: 2,
    baseBoostCredits: 3,
    bonusPct: 50,
    priceUsd: 22,
  },
];

export const MOCK_PROMOS: PromoCode[] = [
  {
    id: "promo-1",
    code: "AUBWEEK26",
    name: "AUB orientation week",
    kind: "percent",
    value: 25,
    usageLimit: 200,
    usageCount: 86,
    startsAt: "2026-08-18",
    expiresAt: "2026-09-12",
    status: "active",
    appliesTo: "basic",
  },
  {
    id: "promo-2",
    code: "BULKFALL",
    name: "Fall landlord bulk",
    kind: "percent",
    value: 15,
    usageLimit: 80,
    usageCount: 31,
    startsAt: "2026-08-01",
    expiresAt: "2026-10-31",
    status: "active",
    appliesTo: "bulk",
  },
  {
    id: "promo-3",
    code: "BROKER10",
    name: "Q3 broker desk",
    kind: "amount",
    value: 10,
    usageLimit: 40,
    usageCount: 12,
    startsAt: "2026-08-01",
    expiresAt: "2026-09-30",
    status: "paused",
    appliesTo: "pro",
  },
  {
    id: "promo-4",
    code: "RAMADAN",
    name: "Ramadan boost nights",
    kind: "amount",
    value: 3,
    usageLimit: 150,
    usageCount: 0,
    startsAt: "2027-02-18",
    expiresAt: "2027-03-20",
    status: "scheduled",
    appliesTo: "all",
  },
  {
    id: "promo-5",
    code: "LAUOPEN",
    name: "LAU open house",
    kind: "percent",
    value: 20,
    usageLimit: 120,
    usageCount: 120,
    startsAt: "2026-06-01",
    expiresAt: "2026-07-15",
    status: "expired",
    appliesTo: "bulk",
  },
  {
    id: "promo-6",
    code: "WELCOME1",
    name: "First paid listing",
    kind: "percent",
    value: 10,
    usageLimit: 500,
    usageCount: 214,
    startsAt: "2026-01-01",
    expiresAt: "2026-12-31",
    status: "active",
    appliesTo: "all",
  },
];
