import type { BroadcastAudience, FeedbackItem, LifecycleNudge } from "./types";

export const MOCK_NUDGES: LifecycleNudge[] = [
  {
    id: "n-welcome",
    title: "Welcome to the platform",
    trigger: "Fires once, 20 minutes after first sign-in.",
    channel: "both",
    audience: "New accounts",
    enabled: true,
    lastFiredAt: "2026-08-25T08:12:00.000Z",
    sent30d: 214,
  },
  {
    id: "n-expiry",
    title: "Listing expiring in 3 days",
    trigger: "Poster has a live listing with 72 hours left.",
    channel: "in_app",
    audience: "Posters",
    enabled: true,
    lastFiredAt: "2026-08-25T06:40:00.000Z",
    sent30d: 86,
  },
  {
    id: "n-profile",
    title: "Finish your profile",
    trigger: "Campus or photo still empty 24 hours after signup.",
    channel: "in_app",
    audience: "Incomplete profiles",
    enabled: true,
    lastFiredAt: "2026-08-24T19:05:00.000Z",
    sent30d: 61,
  },
  {
    id: "n-draft",
    title: "Draft listing sitting idle",
    trigger: "Create wizard abandoned for 48 hours.",
    channel: "email",
    audience: "Posters",
    enabled: false,
    lastFiredAt: "2026-08-11T11:20:00.000Z",
    sent30d: 0,
  },
  {
    id: "n-saved",
    title: "Saved listing still live",
    trigger: "Renter shortlisted a room that is still active after 7 days.",
    channel: "in_app",
    audience: "Renters",
    enabled: true,
    lastFiredAt: "2026-08-25T07:55:00.000Z",
    sent30d: 143,
  },
  {
    id: "n-credit",
    title: "Cash credit still pending",
    trigger: "Whish / OMT slip started, no confirm after 2 hours.",
    channel: "both",
    audience: "Posters",
    enabled: true,
    lastFiredAt: "2026-08-25T09:02:00.000Z",
    sent30d: 19,
  },
  {
    id: "n-verify",
    title: "Verify student email",
    trigger: "Campus domain unconfirmed for 3 days.",
    channel: "email",
    audience: "Unverified",
    enabled: true,
    lastFiredAt: "2026-08-24T21:30:00.000Z",
    sent30d: 37,
  },
  {
    id: "n-dormant",
    title: "Quiet poster with live stock",
    trigger: "No login in 21 days, at least one live listing.",
    channel: "email",
    audience: "Posters",
    enabled: false,
    lastFiredAt: null,
    sent30d: 0,
  },
];

export const MOCK_FEEDBACK: FeedbackItem[] = [
  {
    id: "f-01",
    category: "feature",
    queue: "unread",
    message:
      "Map clustering on Hamra is noisy at exam week. Let me filter by walking minutes to Main Gate instead of a radius pin.",
    createdAt: "2026-08-25T10:18:00.000Z",
    repliedAt: null,
    user: {
      id: "u-01",
      firstName: "Nour",
      lastName: "Haddad",
      email: "nour.haddad@mail.aub.edu",
      campus: "AUB, Hamra",
    },
  },
  {
    id: "f-02",
    category: "bug",
    queue: "unread",
    message:
      "Listing photos stall on 3G in Ras Beirut. Spinner never dies. Had to jump on campus Wi-Fi to finish the foyer post.",
    createdAt: "2026-08-25T09:41:00.000Z",
    repliedAt: null,
    user: {
      id: "u-07",
      firstName: "Rita",
      lastName: "Bazzi",
      email: "rita.bazzi@gmail.com",
      campus: "Balamand, Koura",
    },
  },
  {
    id: "f-03",
    category: "general",
    queue: "unread",
    message:
      "Campus picker listed USEK Kaslik twice and missed NDU Zouk on first load. Refresh fixed it. Still reporting in case it is cache.",
    createdAt: "2026-08-24T22:05:00.000Z",
    repliedAt: null,
    user: {
      id: "u-09",
      firstName: "Layal",
      lastName: "Chami",
      email: "layal.chami@ndu.edu.lb",
      campus: "NDU, Zouk",
    },
  },
  {
    id: "f-04",
    category: "feature",
    queue: "unread",
    message:
      "Arabic UI for my parents. They pay the OMT slip and cannot read the English receipt screen.",
    createdAt: "2026-08-24T16:12:00.000Z",
    repliedAt: null,
    user: {
      id: "u-11",
      firstName: "Tala",
      lastName: "Hobeika",
      email: "tala.hobeika@usek.edu.lb",
      campus: "USEK, Kaslik",
    },
  },
  {
    id: "f-05",
    category: "bug",
    queue: "read",
    message:
      "Electricity hours on the Fanar studio showed 24h EDL after I logged a 18:00–22:00 cut. Renters keep asking if the generator is a lie.",
    createdAt: "2026-08-23T14:28:00.000Z",
    repliedAt: "2026-08-23T18:02:00.000Z",
    user: {
      id: "u-10",
      firstName: "Jad",
      lastName: "Karam",
      email: "jad.karam@hotmail.com",
      campus: "LAU, Beirut",
    },
  },
  {
    id: "f-06",
    category: "feature",
    queue: "read",
    message:
      "WhatsApp deep link from the listing. Students will not email. A wa.me button with the listing title prefilled would close more rooms.",
    createdAt: "2026-08-22T11:09:00.000Z",
    repliedAt: null,
    user: {
      id: "u-12",
      firstName: "Fadi",
      lastName: "Abou Jaoude",
      email: "fadi.aj@gmail.com",
      campus: "USJ, Beirut",
    },
  },
  {
    id: "f-07",
    category: "general",
    queue: "read",
    message:
      "Hamra walk-to-campus filter is the reason I stayed. Keep that. The rest of Beirut can wait.",
    createdAt: "2026-08-21T19:44:00.000Z",
    repliedAt: "2026-08-22T08:15:00.000Z",
    user: {
      id: "u-05",
      firstName: "Sara",
      lastName: "Nassar",
      email: "sara.nassar@usj.edu.lb",
      campus: "USJ, Beirut",
    },
  },
  {
    id: "f-08",
    category: "bug",
    queue: "archived",
    message:
      "Boost toggle on iPhone Safari did nothing. Cleared after the 7-day pin actually applied — leaving this so you can close it.",
    createdAt: "2026-08-18T08:33:00.000Z",
    repliedAt: "2026-08-18T12:50:00.000Z",
    user: {
      id: "u-02",
      firstName: "Karim",
      lastName: "Mansour",
      email: "karim.mansour@gmail.com",
      campus: "LAU, Beirut",
    },
  },
  {
    id: "f-09",
    category: "feature",
    queue: "archived",
    message:
      "Girls-only foyer filter as a first-class chip, not buried in more filters. My mother checks the app for me.",
    createdAt: "2026-08-12T15:20:00.000Z",
    repliedAt: "2026-08-13T09:04:00.000Z",
    user: {
      id: "u-01",
      firstName: "Nour",
      lastName: "Haddad",
      email: "nour.haddad@mail.aub.edu",
      campus: "AUB, Hamra",
    },
  },
];

export const REACH: Record<BroadcastAudience, number> = {
  all: 12840,
  renters: 9120,
  posters: 3720,
  unverified: 840,
};
