/**
 * Demo rental seeds for Skoun browse/map — mirrors create-listing required fields.
 * Coords sit near university gates so PostGIS hub distance is realistic.
 * Photo sources: Unsplash (downloaded at seed time into uploads/).
 */

export const ALL_AMENITY_SLUGS = [
  "ac_all_rooms",
  "ac_salon",
  "washer",
  "study_desk",
  "fridge",
  "microwave",
  "balcony",
  "parking",
  "water_heater_solar",
  "water_heater_electric",
] as const;

export const ALL_HIGHLIGHT_TAG_SLUGS = [
  "walk_to_campus",
  "power_24_7",
  "fiber",
  "quiet_area",
  "newly_renovated",
] as const;

export type ListingSeed = {
  spaceType: "entire_place" | "private_room" | "shared_room";
  propertyType: "apartment" | "studio" | "dormitory" | "house";
  priceBasis: "per_unit_month" | "per_bed_month" | "per_room_month";
  targetAudience: "anyone" | "students_only" | "students_professionals";
  genderRestriction: "anyone" | "boys_only" | "girls_only";
  monthlyRentUsd: number;
  securityDepositUsd: number;
  leaseTerm: "semester" | "months_6" | "months_9" | "year" | "flexible";
  availableFrom: string | null;
  paymentModality: "monthly" | "semester" | "quarterly";
  electricity: "solar" | "generator_24_7" | "scheduled_cuts";
  electricityCutWindows?: { start: string; end: string }[];
  water: "state_well_24_7" | "tank_delivery";
  wifiIncluded: boolean;
  routerUps: boolean;
  elevator24_7: boolean;
  hasElevator: boolean;
  hasSolar: boolean;
  generatorAmperes: number | null;
  generatorIncluded: boolean;
  conciergeIncluded: boolean;
  cookingGasIncluded: boolean;
  amenities: string[];
  bedrooms: number;
  beds: number;
  bathrooms: number;
  maxOccupancy: number;
  furnishingType: "furnished" | "semi" | "unfurnished";
  floorNumber: number;
  areaSqm: number | null;
  smokingPolicy: "inside" | "balcony_only" | "no";
  petsPolicy: "yes" | "cats_only" | "no";
  guestsPolicy: "yes" | "no" | "restricted";
  quietHours: boolean;
  title: string;
  description: string;
  highlightTags: string[];
  listingPosterRole: "landlord" | "student_sublet" | "agent";
  contactName: string;
  contactNumbers: {
    kind: "mobile" | "landline";
    prefix: string;
    subscriber: string;
    e164: string;
    calls: boolean;
    whatsapp: boolean;
  }[];
  area: string;
  landmark: string;
  addressLine: string;
  buildingName: string;
  /** universities.slug — resolved to primaryCampusId at seed time */
  campusSlug: string;
  /** WKT POINT(lng lat) */
  location: string;
  /** Unsplash source URLs (downloaded into /uploads/listings). */
  photoSources: string[];
  photoCaptions: string[];
};

function unsplash(id: string): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
}

const ALL_AMENITIES = [...ALL_AMENITY_SLUGS];
const ALL_HIGHLIGHTS = [...ALL_HIGHLIGHT_TAG_SLUGS];

const SEED_CONTACT = {
  kind: "mobile" as const,
  prefix: "70",
  subscriber: "000001",
  e164: "+96170000001",
  calls: true,
  whatsapp: true,
};

/**
 * Gate pins (from universitySeeds) for reference:
 * AUB            POINT(35.48212 33.89999)
 * LAU Beirut     POINT(35.47750 33.89279)
 * LAU Jbeil      POINT(35.67443 34.11560)
 * USJ Huvelin    POINT(35.50933 33.88984)
 * USJ CSM        POINT(35.51209 33.88233)
 * AUL Dekwaneh   POINT(35.55110 33.87390)
 * BAU Beirut     POINT(35.49713 33.87292)
 * USEK Kaslik    POINT(35.61866 33.98194)
 * NDU Louaize    POINT(35.61371 33.95078)
 * UA Hadat       POINT(35.53617 33.83794)
 * BAU Tripoli    POINT(35.81437 34.43218)
 * USJ CLS Saida  POINT(35.39665 33.57075)
 * USEK Zahle     POINT(35.92602 33.84119)
 */
export const listingSeeds: ListingSeed[] = [
  // ── Hamra / Bliss · AUB ──────────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "studio",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 650,
    securityDepositUsd: 650,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 4,
    areaSqm: 38,
    smokingPolicy: "balcony_only",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "Bliss studio steps from AUB Main Gate",
    description:
      "Bright furnished studio off Bliss Street with generator backup, UPS Wi-Fi, and a walkable commute to AUB. Quiet building, study desk, and balcony light.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Hamra",
    landmark: "Bliss Studio near Main Gate",
    addressLine: "Bliss Street, near AUB Main Gate",
    buildingName: "Bliss Residence",
    campusSlug: "aub",
    location: "POINT(35.4816 33.8989)",
    photoSources: [
      unsplash("photo-1522708323590-d24dbb6b0267"),
      unsplash("photo-1502672260266-1c1ef2d93688"),
      unsplash("photo-1484154218962-a197022b5858"),
    ],
    photoCaptions: ["Living room", "Kitchen", "Bedroom 1"],
  },
  {
    spaceType: "private_room",
    propertyType: "apartment",
    priceBasis: "per_room_month",
    targetAudience: "students_only",
    genderRestriction: "girls_only",
    monthlyRentUsd: 420,
    securityDepositUsd: 420,
    leaseTerm: "months_9",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 15,
    generatorIncluded: true,
    conciergeIncluded: true,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    furnishingType: "furnished",
    floorNumber: 6,
    areaSqm: 18,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "no",
    quietHours: true,
    title: "Girls-only private room off Bliss",
    description:
      "Private bedroom in a girls-only apartment near Bliss. Elevator runs 24/7, fiber Wi-Fi on UPS, and shared kitchen with washer. Ideal for AUB students.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Hamra",
    landmark: "Quiet private room off Bliss",
    addressLine: "Sidani Street, Hamra",
    buildingName: "Sidani Tower",
    campusSlug: "aub",
    location: "POINT(35.4808 33.8978)",
    photoSources: [
      unsplash("photo-1493809842364-78817add7ffb"),
      unsplash("photo-1612320648993-61c1cd604b71"),
      unsplash("photo-1586023492125-27b2c045efd7"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "Living room"],
  },
  {
    spaceType: "shared_room",
    propertyType: "dormitory",
    priceBasis: "per_bed_month",
    targetAudience: "students_only",
    genderRestriction: "girls_only",
    monthlyRentUsd: 280,
    securityDepositUsd: 280,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "semester",
    electricity: "scheduled_cuts",
    electricityCutWindows: [
      { start: "06:00", end: "10:00" },
      { start: "14:00", end: "18:00" },
    ],
    water: "tank_delivery",
    wifiIncluded: true,
    routerUps: false,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 5,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: false,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 4,
    bathrooms: 1,
    maxOccupancy: 4,
    furnishingType: "furnished",
    floorNumber: 2,
    areaSqm: 28,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "no",
    quietHours: true,
    title: "Girls foyer bed near AUB campus",
    description:
      "Shared dorm bed in a supervised girls foyer walking distance to AUB. Scheduled generator windows, tank water delivery, and study desks in-room.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "agent",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Hamra",
    landmark: "Girls foyer bed near AUB",
    addressLine: "Jeanne d'Arc Street, Hamra",
    buildingName: "Campus Foyer Hamra",
    campusSlug: "aub",
    location: "POINT(35.4831 33.9004)",
    photoSources: [
      unsplash("photo-1689043528099-2ba014dd7c64"),
      unsplash("photo-1555854877-bab0e564b8d5"),
      unsplash("photo-1631049307264-da0ec9d70304"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "Building"],
  },
  {
    spaceType: "entire_place",
    propertyType: "apartment",
    priceBasis: "per_unit_month",
    targetAudience: "anyone",
    genderRestriction: "anyone",
    monthlyRentUsd: 1100,
    securityDepositUsd: 2200,
    leaseTerm: "year",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "solar",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: true,
    generatorAmperes: 15,
    generatorIncluded: true,
    conciergeIncluded: true,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 8,
    areaSqm: 65,
    smokingPolicy: "balcony_only",
    petsPolicy: "cats_only",
    guestsPolicy: "yes",
    quietHours: false,
    title: "Sunny 1BR steps from Hamra Street",
    description:
      "Full one-bedroom apartment with solar power, 24/7 elevator, parking, and fiber internet. Open to students and professionals near Hamra's cafes and AUB.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Hamra",
    landmark: "Sunny 1BR steps from Hamra Street",
    addressLine: "Hamra Street, near Pizza Hut",
    buildingName: "Hamra Heights",
    campusSlug: "aub",
    location: "POINT(35.4828 33.8965)",
    photoSources: [
      unsplash("photo-1560448204-e02f11c3d0e2"),
      unsplash("photo-1583847268964-b28dc8f51f92"),
      unsplash("photo-1560185127-6ed189bf02f4"),
    ],
    photoCaptions: ["Living room", "Kitchen", "Bedroom 1"],
  },

  // ── Byblos · LAU Jbeil ───────────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "studio",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 550,
    securityDepositUsd: 550,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 1,
    areaSqm: 32,
    smokingPolicy: "balcony_only",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "LAU-ready studio in Old Souk area",
    description:
      "Compact furnished studio near LAU Byblos with generator included, UPS Wi-Fi, and a short walk to campus. Quiet nights after Old Souk closes.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Byblos",
    landmark: "LAU-ready studio in Old Souk area",
    addressLine: "Old Souk Road, Byblos",
    buildingName: "Souk Studio House",
    campusSlug: "lau-jbeil",
    location: "POINT(35.6474 34.1206)",
    photoSources: [
      unsplash("photo-1606074280798-2dabb75ce10c"),
      unsplash("photo-1675279200694-8529c73b1fd0"),
      unsplash("photo-1522771739844-6a9f6d5f14af"),
    ],
    photoCaptions: ["Living room", "Kitchen", "View"],
  },
  {
    spaceType: "shared_room",
    propertyType: "dormitory",
    priceBasis: "per_bed_month",
    targetAudience: "students_only",
    genderRestriction: "boys_only",
    monthlyRentUsd: 250,
    securityDepositUsd: 250,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "scheduled_cuts",
    electricityCutWindows: [{ start: "08:00", end: "16:00" }],
    water: "tank_delivery",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 5,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: false,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 3,
    bathrooms: 1,
    maxOccupancy: 3,
    furnishingType: "furnished",
    floorNumber: 0,
    areaSqm: 24,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "no",
    quietHours: true,
    title: "Boys foyer bed near LAU Byblos",
    description:
      "Affordable boys-only foyer bed near LAU Jbeil. Shared room with study desks, tank water, and router UPS so Wi-Fi stays up during cuts.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "agent",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Byblos",
    landmark: "Boys foyer near LAU Byblos",
    addressLine: "Near LAU Byblos main entrance",
    buildingName: "LAU Boys Residence",
    campusSlug: "lau-jbeil",
    location: "POINT(35.6490 34.1224)",
    photoSources: [
      unsplash("photo-1555854877-bab0e564b8d5"),
      unsplash("photo-1738168279272-c08d6dd22002"),
      unsplash("photo-1595526114035-0d45ed16cfbf"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "Building"],
  },

  // ── Achrafieh / Huvelin · USJ ────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "apartment",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 950,
    securityDepositUsd: 950,
    leaseTerm: "months_9",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 15,
    generatorIncluded: true,
    conciergeIncluded: true,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    maxOccupancy: 3,
    furnishingType: "furnished",
    floorNumber: 5,
    areaSqm: 85,
    smokingPolicy: "balcony_only",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "Huvelin flat near USJ campus",
    description:
      "Two-bedroom furnished flat a short walk from USJ Huvelin. Generator 24/7, concierge, parking, and fiber internet for remote classes.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Achrafieh",
    landmark: "Huvelin flat near USJ campus",
    addressLine: "Rue Huvelin, Achrafieh",
    buildingName: "Huvelin Court",
    campusSlug: "usj-huvelin",
    location: "POINT(35.5192 33.8906)",
    photoSources: [
      unsplash("photo-1613575831056-0acd5da8f085"),
      unsplash("photo-1665249934445-1de680641f50"),
      unsplash("photo-1616486338812-3dadae4b4ace"),
    ],
    photoCaptions: ["Living room", "Bedroom 1", "Kitchen"],
  },
  {
    spaceType: "private_room",
    propertyType: "apartment",
    priceBasis: "per_room_month",
    targetAudience: "students_only",
    genderRestriction: "girls_only",
    monthlyRentUsd: 380,
    securityDepositUsd: 380,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "solar",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: false,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: true,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    furnishingType: "semi",
    floorNumber: 3,
    areaSqm: 16,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "Private room by Sassine and Huvelin",
    description:
      "Quiet girls-only private room between Sassine and Huvelin with solar backup, elevator, and a furnished study corner for USJ students.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "student_sublet",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Achrafieh",
    landmark: "Private room by Sassine & Huvelin",
    addressLine: "Near Sassine Square, Achrafieh",
    buildingName: "Sassine Residence",
    campusSlug: "usj-huvelin",
    location: "POINT(35.5178 33.8919)",
    photoSources: [
      unsplash("photo-1564078516393-cf04bd966897"),
      unsplash("photo-1614607242094-b1b2cf769ff3"),
      unsplash("photo-1505693416388-ac5ce068fe85"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "View"],
  },

  // ── Fanar & Dekwaneh · AUL ───────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "studio",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 480,
    securityDepositUsd: 480,
    leaseTerm: "months_6",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "tank_delivery",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 2,
    areaSqm: 35,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: false,
    title: "Compact studio near AUL Dekwaneh",
    description:
      "Student studio in Fanar with generator, UPS Wi-Fi, and tank water delivery. Fully furnished with balcony and parking — short hop to AUL Dekwaneh.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Fanar",
    landmark: "Compact studio near AUL Dekwaneh",
    addressLine: "Main Road, Fanar",
    buildingName: "Fanar Student House",
    campusSlug: "aul-dekwaneh",
    location: "POINT(35.5676 33.8789)",
    photoSources: [
      unsplash("photo-1631049307264-da0ec9d70304"),
      unsplash("photo-1522708323590-d24dbb6b0267"),
      unsplash("photo-1493809842364-78817add7ffb"),
    ],
    photoCaptions: ["Living room", "Kitchen", "Bedroom 1"],
  },
  {
    spaceType: "private_room",
    propertyType: "house",
    priceBasis: "per_room_month",
    targetAudience: "students_professionals",
    genderRestriction: "boys_only",
    monthlyRentUsd: 320,
    securityDepositUsd: 320,
    leaseTerm: "flexible",
    availableFrom: "2026-10-01",
    paymentModality: "monthly",
    electricity: "scheduled_cuts",
    electricityCutWindows: [
      { start: "10:00", end: "14:00" },
      { start: "22:00", end: "02:00" },
    ],
    water: "tank_delivery",
    wifiIncluded: true,
    routerUps: false,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 5,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    furnishingType: "semi",
    floorNumber: 1,
    areaSqm: 14,
    smokingPolicy: "inside",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: false,
    title: "Affordable boys room in Dekwaneh",
    description:
      "Budget private room in a boys-only house in Dekwaneh. Scheduled cuts with generator amps, tank water, and a short walk to AUL Dekwaneh campus.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Dekwaneh",
    landmark: "Affordable room in Dekwaneh",
    addressLine: "Dekwaneh main road",
    buildingName: "Dekwaneh Shared House",
    campusSlug: "aul-dekwaneh",
    location: "POINT(35.5448 33.8752)",
    photoSources: [
      unsplash("photo-1595526114035-0d45ed16cfbf"),
      unsplash("photo-1484154218962-a197022b5858"),
      unsplash("photo-1586023492125-27b2c045efd7"),
    ],
    photoCaptions: ["Bedroom 1", "Kitchen", "Bathroom"],
  },

  // ── LAU Beirut · Ras Beirut ──────────────────────────────────────
  {
    spaceType: "private_room",
    propertyType: "apartment",
    priceBasis: "per_room_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 450,
    securityDepositUsd: 450,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    furnishingType: "furnished",
    floorNumber: 7,
    areaSqm: 17,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "Private room near LAU Beirut gate",
    description:
      "Furnished private room in Ras Beirut minutes from LAU Beirut. Generator 24/7, UPS Wi-Fi, and elevator access for late library nights.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Ras Beirut",
    landmark: "Private room near LAU Beirut",
    addressLine: "Near LAU Beirut, Ras Beirut",
    buildingName: "Qoreitem Residences",
    campusSlug: "lau-beirut",
    location: "POINT(35.4769 33.8932)",
    photoSources: [
      unsplash("photo-1502672260266-1c1ef2d93688"),
      unsplash("photo-1522771739844-6a9f6d5f14af"),
      unsplash("photo-1484154218962-a197022b5858"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "Living room"],
  },

  // ── BAU Beirut · Jnah ────────────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "apartment",
    priceBasis: "per_unit_month",
    targetAudience: "students_professionals",
    genderRestriction: "anyone",
    monthlyRentUsd: 900,
    securityDepositUsd: 900,
    leaseTerm: "year",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "solar",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: true,
    generatorAmperes: 15,
    generatorIncluded: true,
    conciergeIncluded: true,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    maxOccupancy: 4,
    furnishingType: "furnished",
    floorNumber: 9,
    areaSqm: 95,
    smokingPolicy: "balcony_only",
    petsPolicy: "cats_only",
    guestsPolicy: "yes",
    quietHours: false,
    title: "Sea-view 2BR near BAU Beirut",
    description:
      "Spacious two-bedroom apartment near BAU Beirut with solar power, parking, and fiber. Open to students and young professionals.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "agent",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Jnah",
    landmark: "Sea-view flat near BAU",
    addressLine: "Airport Road side, Jnah",
    buildingName: "Jnah Horizon",
    campusSlug: "bau-beirut",
    location: "POINT(35.4964 33.8735)",
    photoSources: [
      unsplash("photo-1560448204-e02f11c3d0e2"),
      unsplash("photo-1583847268964-b28dc8f51f92"),
      unsplash("photo-1560185127-6ed189bf02f4"),
    ],
    photoCaptions: ["Living room", "Bedroom 1", "Kitchen"],
  },

  // ── USEK · Kaslik ────────────────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "studio",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 520,
    securityDepositUsd: 520,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 3,
    areaSqm: 30,
    smokingPolicy: "balcony_only",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "Kaslik studio walk to USEK",
    description:
      "Compact studio in Kaslik with generator backup and UPS Wi-Fi. Five-minute walk to USEK campus gates and Jounieh service lines.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Kaslik",
    landmark: "Studio walk to USEK",
    addressLine: "Kaslik highway side street",
    buildingName: "Kaslik Student Suites",
    campusSlug: "usek-kaslik",
    location: "POINT(35.6179 33.9824)",
    photoSources: [
      unsplash("photo-1606074280798-2dabb75ce10c"),
      unsplash("photo-1675279200694-8529c73b1fd0"),
      unsplash("photo-1522708323590-d24dbb6b0267"),
    ],
    photoCaptions: ["Living room", "Kitchen", "View"],
  },

  // ── NDU · Zouk Mosbeh ────────────────────────────────────────────
  {
    spaceType: "shared_room",
    propertyType: "dormitory",
    priceBasis: "per_bed_month",
    targetAudience: "students_only",
    genderRestriction: "girls_only",
    monthlyRentUsd: 260,
    securityDepositUsd: 260,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "semester",
    electricity: "scheduled_cuts",
    electricityCutWindows: [
      { start: "07:00", end: "11:00" },
      { start: "15:00", end: "19:00" },
    ],
    water: "tank_delivery",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 5,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: false,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 4,
    bathrooms: 1,
    maxOccupancy: 4,
    furnishingType: "furnished",
    floorNumber: 1,
    areaSqm: 26,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "no",
    quietHours: true,
    title: "Girls foyer bed near NDU Louaize",
    description:
      "Shared girls foyer bed close to NDU Louaize. Study desks, router UPS during cuts, and tank water delivery included.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "agent",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Zouk Mosbeh",
    landmark: "Girls foyer near NDU",
    addressLine: "Near NDU main gate, Zouk Mosbeh",
    buildingName: "Louaize Girls House",
    campusSlug: "ndu-louaize",
    location: "POINT(35.6131 33.9513)",
    photoSources: [
      unsplash("photo-1689043528099-2ba014dd7c64"),
      unsplash("photo-1555854877-bab0e564b8d5"),
      unsplash("photo-1631049307264-da0ec9d70304"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "Building"],
  },

  // ── UA Hadat · Furn El Chebbak ───────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "apartment",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 780,
    securityDepositUsd: 780,
    leaseTerm: "months_9",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 15,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 4,
    areaSqm: 58,
    smokingPolicy: "balcony_only",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "1BR near UA Hadat Baabda",
    description:
      "One-bedroom apartment between Furn El Chebbak and Hadat with full generator, fiber, and parking. Built for UA commuting students.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Furn El Chebbak",
    landmark: "1BR near UA Hadat",
    addressLine: "Furn El Chebbak toward Hadat",
    buildingName: "Hadat View",
    campusSlug: "ua-hadat-baabda",
    location: "POINT(35.5354 33.8386)",
    photoSources: [
      unsplash("photo-1493809842364-78817add7ffb"),
      unsplash("photo-1502672260266-1c1ef2d93688"),
      unsplash("photo-1560448204-e02f11c3d0e2"),
    ],
    photoCaptions: ["Living room", "Bedroom 1", "Kitchen"],
  },

  // ── USJ CSM · Badaro ─────────────────────────────────────────────
  {
    spaceType: "private_room",
    propertyType: "apartment",
    priceBasis: "per_room_month",
    targetAudience: "students_only",
    genderRestriction: "boys_only",
    monthlyRentUsd: 360,
    securityDepositUsd: 360,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "solar",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: false,
    elevator24_7: false,
    hasElevator: true,
    hasSolar: true,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    furnishingType: "semi",
    floorNumber: 2,
    areaSqm: 15,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: true,
    title: "Boys room near USJ Sciences",
    description:
      "Boys-only private room in Badaro walking distance to USJ Sciences. Solar backup, study desk, and quiet hours after 11pm.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "student_sublet",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Badaro",
    landmark: "Boys room near USJ CSM",
    addressLine: "Badaro, near USJ Sciences",
    buildingName: "Badaro Shared Flat",
    campusSlug: "usj-csm",
    location: "POINT(35.5115 33.8828)",
    photoSources: [
      unsplash("photo-1612320648993-61c1cd604b71"),
      unsplash("photo-1616486338812-3dadae4b4ace"),
      unsplash("photo-1586023492125-27b2c045efd7"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "Living room"],
  },

  // ── BAU Tripoli ──────────────────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "studio",
    priceBasis: "per_unit_month",
    targetAudience: "students_only",
    genderRestriction: "anyone",
    monthlyRentUsd: 400,
    securityDepositUsd: 400,
    leaseTerm: "months_6",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "generator_24_7",
    water: "tank_delivery",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 1,
    areaSqm: 34,
    smokingPolicy: "balcony_only",
    petsPolicy: "no",
    guestsPolicy: "restricted",
    quietHours: false,
    title: "Tripoli studio near BAU campus",
    description:
      "Affordable furnished studio near BAU Tripoli with generator, UPS Wi-Fi, and tank water. Easy service ride into the city.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Tripoli",
    landmark: "Studio near BAU Tripoli",
    addressLine: "Near BAU Tripoli campus",
    buildingName: "Tripoli Student Studio",
    campusSlug: "bau-tripoli",
    location: "POINT(35.8138 34.4326)",
    photoSources: [
      unsplash("photo-1484154218962-a197022b5858"),
      unsplash("photo-1522708323590-d24dbb6b0267"),
      unsplash("photo-1606074280798-2dabb75ce10c"),
    ],
    photoCaptions: ["Living room", "Kitchen", "Bedroom 1"],
  },

  // ── USJ CLS · Saida ──────────────────────────────────────────────
  {
    spaceType: "private_room",
    propertyType: "house",
    priceBasis: "per_room_month",
    targetAudience: "students_only",
    genderRestriction: "girls_only",
    monthlyRentUsd: 300,
    securityDepositUsd: 300,
    leaseTerm: "semester",
    availableFrom: null,
    paymentModality: "monthly",
    electricity: "scheduled_cuts",
    electricityCutWindows: [{ start: "09:00", end: "15:00" }],
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: false,
    hasSolar: false,
    generatorAmperes: 5,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 1,
    furnishingType: "furnished",
    floorNumber: 0,
    areaSqm: 14,
    smokingPolicy: "no",
    petsPolicy: "no",
    guestsPolicy: "no",
    quietHours: true,
    title: "Girls room near USJ Saida",
    description:
      "Quiet girls-only room in a family house near USJ CLS Saida. Generator amps, UPS Wi-Fi, and walkable campus commute.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Saida",
    landmark: "Girls room near USJ Saida",
    addressLine: "Near USJ CLS, Saida",
    buildingName: "Saida Family House",
    campusSlug: "usj-cls",
    location: "POINT(35.3962 33.5712)",
    photoSources: [
      unsplash("photo-1564078516393-cf04bd966897"),
      unsplash("photo-1614607242094-b1b2cf769ff3"),
      unsplash("photo-1505693416388-ac5ce068fe85"),
    ],
    photoCaptions: ["Bedroom 1", "Bathroom", "View"],
  },

  // ── USEK · Zahle ─────────────────────────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "apartment",
    priceBasis: "per_unit_month",
    targetAudience: "anyone",
    genderRestriction: "anyone",
    monthlyRentUsd: 700,
    securityDepositUsd: 1400,
    leaseTerm: "year",
    availableFrom: null,
    paymentModality: "quarterly",
    electricity: "generator_24_7",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: true,
    hasElevator: true,
    hasSolar: false,
    generatorAmperes: 15,
    generatorIncluded: true,
    conciergeIncluded: true,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    maxOccupancy: 3,
    furnishingType: "furnished",
    floorNumber: 5,
    areaSqm: 80,
    smokingPolicy: "balcony_only",
    petsPolicy: "yes",
    guestsPolicy: "yes",
    quietHours: false,
    title: "Zahle 2BR near USEK campus",
    description:
      "Bright two-bedroom flat near USEK Zahle with generator 24/7, elevator, parking, and fiber. Suitable for roommates or a small family.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "landlord",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Zahle",
    landmark: "2BR near USEK Zahle",
    addressLine: "Near USEK Zahle campus",
    buildingName: "Bekaa Residences",
    campusSlug: "usek-zahle",
    location: "POINT(35.9254 33.8416)",
    photoSources: [
      unsplash("photo-1613575831056-0acd5da8f085"),
      unsplash("photo-1665249934445-1de680641f50"),
      unsplash("photo-1583847268964-b28dc8f51f92"),
    ],
    photoCaptions: ["Living room", "Bedroom 1", "Kitchen"],
  },

  // ── Mar Mikhael · USJ Huvelin commute ────────────────────────────
  {
    spaceType: "entire_place",
    propertyType: "studio",
    priceBasis: "per_unit_month",
    targetAudience: "students_professionals",
    genderRestriction: "anyone",
    monthlyRentUsd: 720,
    securityDepositUsd: 720,
    leaseTerm: "flexible",
    availableFrom: "2026-11-01",
    paymentModality: "monthly",
    electricity: "solar",
    water: "state_well_24_7",
    wifiIncluded: true,
    routerUps: true,
    elevator24_7: false,
    hasElevator: true,
    hasSolar: true,
    generatorAmperes: 10,
    generatorIncluded: true,
    conciergeIncluded: false,
    cookingGasIncluded: true,
    amenities: ALL_AMENITIES,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    maxOccupancy: 2,
    furnishingType: "furnished",
    floorNumber: 6,
    areaSqm: 42,
    smokingPolicy: "balcony_only",
    petsPolicy: "cats_only",
    guestsPolicy: "restricted",
    quietHours: false,
    title: "Mar Mikhael loft-style studio",
    description:
      "Newly renovated loft-style studio in Mar Mikhael with solar power and fiber. Short service hop to USJ Huvelin and nightlife downstairs.",
    highlightTags: ALL_HIGHLIGHTS,
    listingPosterRole: "student_sublet",
    contactName: "Skoun Demo Host",
    contactNumbers: [SEED_CONTACT],
    area: "Mar Mikhael",
    landmark: "Loft studio in Mar Mikhael",
    addressLine: "Armenia Street, Mar Mikhael",
    buildingName: "Armenia Lofts",
    campusSlug: "usj-huvelin",
    location: "POINT(35.5278 33.8991)",
    photoSources: [
      unsplash("photo-1738168279272-c08d6dd22002"),
      unsplash("photo-1595526114035-0d45ed16cfbf"),
      unsplash("photo-1560185127-6ed189bf02f4"),
    ],
    photoCaptions: ["Living room", "Kitchen", "View"],
  },
];
