import type { AcademicDomain, KycCase, ScamAlert } from "./types";

export const MOCK_KYC: KycCase[] = [
  {
    id: "kyc-01",
    queue: "pending",
    submittedAt: "2026-08-25T08:12:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-02",
      firstName: "Karim",
      lastName: "Mansour",
      email: "karim.mansour@gmail.com",
      phone: "+961 3 441 208",
      accountStatus: "active",
      listingCount: 4,
      area: "Hamra",
    },
    badge: "none",
    documents: [
      {
        id: "d-01-1",
        kind: "national_id",
        side: "front",
        issuedOn: "2019-04-11",
        numberMasked: "LB •••• 4412",
        extra: "Beirut",
      },
      {
        id: "d-01-2",
        kind: "national_id",
        side: "back",
        issuedOn: "2019-04-11",
        numberMasked: "LB •••• 4412",
        extra: "Hamra, Beirut",
      },
      {
        id: "d-01-3",
        kind: "property_deed",
        side: "full",
        issuedOn: "2021-06-02",
        numberMasked: "Cadastre ••• 1184",
        extra: "Hamra · Sect. 4 · Plot 1184",
      },
    ],
  },
  {
    id: "kyc-02",
    queue: "pending",
    submittedAt: "2026-08-24T19:40:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-07",
      firstName: "Rita",
      lastName: "Bazzi",
      email: "rita.bazzi@gmail.com",
      phone: "+961 71 882 441",
      accountStatus: "active",
      listingCount: 1,
      area: "Hamra",
    },
    badge: "none",
    documents: [
      {
        id: "d-02-1",
        kind: "passport",
        side: "front",
        issuedOn: "2023-01-18",
        numberMasked: "LR •••• 9031",
        extra: "Lebanese Republic",
      },
    ],
  },
  {
    id: "kyc-03",
    queue: "pending",
    submittedAt: "2026-08-24T11:05:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-06",
      firstName: "Hassan",
      lastName: "Fares",
      email: "hassan.fares@skoun.dev",
      phone: "+961 71 445 902",
      accountStatus: "active",
      listingCount: 3,
      area: "Hamra",
    },
    badge: "none",
    documents: [
      {
        id: "d-03-1",
        kind: "national_id",
        side: "front",
        issuedOn: "2016-09-22",
        numberMasked: "LB •••• 7703",
        extra: "Tripoli",
      },
      {
        id: "d-03-2",
        kind: "property_deed",
        side: "full",
        issuedOn: "2024-11-09",
        numberMasked: "Cadastre ••• 0091",
        extra: "Hamra · Sect. 2 · Plot 91",
      },
    ],
  },
  {
    id: "kyc-04",
    queue: "pending",
    submittedAt: "2026-08-23T16:22:00.000Z",
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-12",
      firstName: "Nadine",
      lastName: "Harb",
      email: "nadine.harb@outlook.com",
      phone: "+961 76 210 448",
      accountStatus: "active",
      listingCount: 2,
      area: "Ras Beirut",
    },
    badge: "none",
    documents: [
      {
        id: "d-04-1",
        kind: "national_id",
        side: "front",
        issuedOn: "2020-02-03",
        numberMasked: "LB •••• 2281",
        extra: "Beirut",
      },
      {
        id: "d-04-2",
        kind: "national_id",
        side: "back",
        issuedOn: "2020-02-03",
        numberMasked: "LB •••• 2281",
        extra: "Ras Beirut",
      },
    ],
  },
  {
    id: "kyc-05",
    queue: "verified",
    submittedAt: "2026-08-12T09:18:00.000Z",
    reviewedAt: "2026-08-12T14:02:00.000Z",
    reviewer: "Lina A.",
    note: "Deed matches cadastre extract. Badge granted.",
    poster: {
      id: "u-15",
      firstName: "Jad",
      lastName: "Karam",
      email: "jad.karam@gmail.com",
      phone: "+961 3 118 774",
      accountStatus: "active",
      listingCount: 5,
      area: "Achrafieh",
    },
    badge: "verified",
    documents: [
      {
        id: "d-05-1",
        kind: "national_id",
        side: "front",
        issuedOn: "2018-07-30",
        numberMasked: "LB •••• 5510",
        extra: "Beirut",
      },
      {
        id: "d-05-2",
        kind: "property_deed",
        side: "full",
        issuedOn: "2015-03-14",
        numberMasked: "Cadastre ••• 4402",
        extra: "Achrafieh · Sect. 7 · Plot 4402",
      },
    ],
  },
  {
    id: "kyc-06",
    queue: "rejected",
    submittedAt: "2026-08-08T13:44:00.000Z",
    reviewedAt: "2026-08-09T10:11:00.000Z",
    reviewer: "Lina A.",
    note: "Deed photo cropped. Name on ID does not match Clerk account.",
    poster: {
      id: "u-04",
      firstName: "Elie",
      lastName: "Saad",
      email: "elie.saad@outlook.com",
      phone: "+961 70 993 221",
      accountStatus: "banned",
      listingCount: 6,
      area: "Hamra",
    },
    badge: "revoked",
    documents: [
      {
        id: "d-06-1",
        kind: "national_id",
        side: "front",
        issuedOn: "2014-12-01",
        numberMasked: "LB •••• 0198",
        extra: "Zahle",
      },
    ],
  },
];

export const MOCK_ALERTS: ScamAlert[] = [
  {
    id: "al-01",
    pattern: "shared_ip",
    severity: "critical",
    status: "open",
    createdAt: "2026-08-25T07:48:00.000Z",
    title: "Four poster accounts from one Ogero IP",
    detail:
      "Created within 36 hours. Same /24, Hamra listings, overlapping WhatsApp copy.",
    signal: "178.135.42.18",
    accounts: [
      {
        id: "u-06",
        firstName: "Hassan",
        lastName: "Fares",
        email: "hassan.fares@skoun.dev",
        phone: "+961 71 445 902",
        accountStatus: "active",
      },
      {
        id: "u-21",
        firstName: "Omar",
        lastName: "Fares",
        email: "omar.fares.lets@gmail.com",
        phone: "+961 71 445 910",
        accountStatus: "active",
      },
      {
        id: "u-22",
        firstName: "Sami",
        lastName: "Nader",
        email: "sami.nader.rooms@gmail.com",
        phone: "+961 81 332 019",
        accountStatus: "active",
      },
      {
        id: "u-23",
        firstName: "Hiba",
        lastName: "Nader",
        email: "hiba.nader.stay@gmail.com",
        phone: "+961 81 332 020",
        accountStatus: "active",
      },
    ],
  },
  {
    id: "al-02",
    pattern: "duplicate_phone",
    severity: "high",
    status: "open",
    createdAt: "2026-08-24T21:16:00.000Z",
    title: "Same Lebanese mobile on two posters",
    detail:
      "Touch verified on both Clerk accounts. Listings in Hamra and Jounieh under different names.",
    signal: "+961 71 445 902",
    accounts: [
      {
        id: "u-06",
        firstName: "Hassan",
        lastName: "Fares",
        email: "hassan.fares@skoun.dev",
        phone: "+961 71 445 902",
        accountStatus: "active",
      },
      {
        id: "u-24",
        firstName: "Karim",
        lastName: "Fares",
        email: "k.fares.housing@gmail.com",
        phone: "+961 71 445 902",
        accountStatus: "active",
      },
    ],
  },
  {
    id: "al-03",
    pattern: "cloned_listings",
    severity: "critical",
    status: "open",
    createdAt: "2026-08-24T15:02:00.000Z",
    title: "Cloned Bliss studio photos",
    detail:
      "Three live posts share the same six photo hashes. Contact numbers differ by one digit.",
    signal: "hash · 6 photos",
    accounts: [
      {
        id: "u-07",
        firstName: "Rita",
        lastName: "Bazzi",
        email: "rita.bazzi@gmail.com",
        phone: "+961 71 882 441",
        accountStatus: "active",
      },
      {
        id: "u-25",
        firstName: "Rania",
        lastName: "Bazzi",
        email: "rania.bliss.studio@gmail.com",
        phone: "+961 71 882 445",
        accountStatus: "active",
      },
    ],
  },
  {
    id: "al-04",
    pattern: "rapid_signup",
    severity: "watch",
    status: "open",
    createdAt: "2026-08-23T22:41:00.000Z",
    title: "Burst of renter accounts from one IP",
    detail:
      "Nine signups in 14 minutes. All used gmail aliases. No listings yet.",
    signal: "46.19.88.12",
    accounts: [
      {
        id: "u-31",
        firstName: "Tarek",
        lastName: "Younes",
        email: "tarek.y.rooms+1@gmail.com",
        phone: "+961 70 118 002",
        accountStatus: "active",
      },
      {
        id: "u-32",
        firstName: "Tarek",
        lastName: "Younes",
        email: "tarek.y.rooms+2@gmail.com",
        phone: "+961 70 118 003",
        accountStatus: "active",
      },
      {
        id: "u-33",
        firstName: "Tarek",
        lastName: "Younes",
        email: "tarek.y.rooms+3@gmail.com",
        phone: "+961 70 118 004",
        accountStatus: "active",
      },
    ],
  },
  {
    id: "al-05",
    pattern: "duplicate_phone",
    severity: "high",
    status: "reviewing",
    createdAt: "2026-08-22T10:08:00.000Z",
    title: "Renter and poster share one Touch line",
    detail:
      "Student email on renter. Poster account lists a foyer bed near AUB.",
    signal: "+961 76 554 019",
    accounts: [
      {
        id: "u-01",
        firstName: "Nour",
        lastName: "Haddad",
        email: "nour.haddad@mail.aub.edu",
        phone: "+961 76 554 019",
        accountStatus: "active",
      },
      {
        id: "u-26",
        firstName: "N. H.",
        lastName: "Lets",
        email: "nh.lets.hamra@gmail.com",
        phone: "+961 76 554 019",
        accountStatus: "active",
      },
    ],
  },
];

export const MOCK_DOMAINS: AcademicDomain[] = [
  {
    id: "dom-01",
    domain: "aub.edu.lb",
    institution: "AUB",
    studentCount: 412,
  },
  {
    id: "dom-02",
    domain: "mail.aub.edu",
    institution: "AUB",
    studentCount: 186,
  },
  {
    id: "dom-03",
    domain: "lau.edu.lb",
    institution: "LAU",
    studentCount: 274,
  },
  {
    id: "dom-04",
    domain: "usj.edu.lb",
    institution: "USJ",
    studentCount: 198,
  },
  {
    id: "dom-05",
    domain: "ndu.edu.lb",
    institution: "NDU",
    studentCount: 91,
  },
  {
    id: "dom-06",
    domain: "usek.edu.lb",
    institution: "USEK",
    studentCount: 64,
  },
];
