import {
  ANCHOR_ISO,
  type AcademicDomain,
  type KycCase,
  type ScamAlert,
} from "./types";

const anchorMs = new Date(ANCHOR_ISO).getTime();
const hours = (n: number) =>
  new Date(anchorMs - n * 60 * 60 * 1000).toISOString();

const DOC = {
  idFront:
    "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=70",
  idBack:
    "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=70",
  passport:
    "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=70",
  deed: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=70",
};

export const MOCK_KYC: KycCase[] = [
  {
    id: "kyc-01",
    queue: "pending",
    submittedAt: hours(8),
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-01",
      firstName: "Karim",
      lastName: "Nassar",
      email: "karim.nassar@gmail.com",
      phone: "+961 3 441 220",
      accountStatus: "active",
      warningCount: 0,
      listingCount: 3,
      area: "Hamra",
    },
    badge: "none",
    documents: [
      {
        id: "doc-01a",
        kind: "national_id",
        side: "front",
        issuedOn: "2022-03-14",
        numberMasked: "ID ··· 4481",
        url: DOC.idFront,
      },
      {
        id: "doc-01b",
        kind: "national_id",
        side: "back",
        issuedOn: "2022-03-14",
        numberMasked: "ID ··· 4481",
        extra: "Address line matches Hamra listing.",
        url: DOC.idBack,
      },
    ],
    history: [],
  },
  {
    id: "kyc-02",
    queue: "pending",
    submittedAt: hours(18),
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-04",
      firstName: "Maya",
      lastName: "Khoury",
      email: "maya.khoury@outlook.com",
      phone: "+961 70 228 441",
      accountStatus: "restricted",
      warningCount: 1,
      listingCount: 1,
      area: "Achrafieh",
    },
    badge: "none",
    documents: [
      {
        id: "doc-02a",
        kind: "passport",
        side: "full",
        issuedOn: "2024-01-09",
        numberMasked: "P ··· 7712",
        extra: "Photo glare on MRZ. Name matches account.",
        url: DOC.passport,
      },
    ],
    history: [
      {
        id: "kh-02a",
        kind: "warn",
        note: "Warned from scam cluster al-02 (shared phone).",
        at: hours(40),
        actor: "Lina Haddad",
      },
    ],
  },
  {
    id: "kyc-03",
    queue: "verified",
    submittedAt: hours(72),
    reviewedAt: hours(60),
    reviewer: "Lina Haddad",
    note: "ID + deed match listing address. Granted Verified Poster.",
    poster: {
      id: "u-07",
      firstName: "Rami",
      lastName: "Saad",
      email: "rami.saad@gmail.com",
      phone: "+961 3 902 118",
      accountStatus: "active",
      warningCount: 0,
      listingCount: 5,
      area: "Verdun",
    },
    badge: "verified",
    documents: [
      {
        id: "doc-03a",
        kind: "national_id",
        side: "front",
        issuedOn: "2021-11-02",
        numberMasked: "ID ··· 1190",
        url: DOC.idFront,
      },
      {
        id: "doc-03b",
        kind: "property_deed",
        side: "full",
        issuedOn: "2019-06-20",
        numberMasked: "Deed ··· 3304",
        extra: "Cadastre Verdun, plot matches listing.",
        url: DOC.deed,
      },
    ],
    history: [
      {
        id: "kh-03a",
        kind: "grant_badge",
        note: "ID + deed match listing address. Granted Verified Poster.",
        at: hours(60),
        actor: "Lina Haddad",
      },
    ],
  },
  {
    id: "kyc-04",
    queue: "pending",
    submittedAt: hours(5),
    reviewedAt: null,
    reviewer: null,
    note: null,
    poster: {
      id: "u-13",
      firstName: "Nadine",
      lastName: "Harb",
      email: "nadine.harb@gmail.com",
      phone: "+961 71 550 330",
      accountStatus: "active",
      warningCount: 0,
      listingCount: 2,
      area: "Gemmayze",
    },
    badge: "none",
    documents: [
      {
        id: "doc-04a",
        kind: "national_id",
        side: "front",
        issuedOn: "2023-08-01",
        numberMasked: "ID ··· 6620",
        url: DOC.idFront,
      },
      {
        id: "doc-04b",
        kind: "national_id",
        side: "back",
        issuedOn: "2023-08-01",
        numberMasked: "ID ··· 6620",
        extra: "Cropped edges. Ask for a recapture if name is unreadable.",
        url: DOC.idBack,
      },
    ],
    history: [],
  },
  {
    id: "kyc-05",
    queue: "rejected",
    submittedAt: hours(96),
    reviewedAt: hours(80),
    reviewer: "Nour Fakhoury",
    note: "Deed photo is a screenshot of an old listing. Rejected.",
    poster: {
      id: "u-10",
      firstName: "Jad",
      lastName: "Karam",
      email: "jad.karam@hotmail.com",
      phone: "+961 76 441 009",
      accountStatus: "active",
      warningCount: 0,
      listingCount: 1,
      area: "Jounieh",
    },
    badge: "none",
    documents: [
      {
        id: "doc-05a",
        kind: "property_deed",
        side: "full",
        issuedOn: "2016-04-12",
        numberMasked: "Deed ··· 8811",
        extra: "Watermark from a classifieds site visible at 200%.",
        url: DOC.deed,
      },
    ],
    history: [
      {
        id: "kh-05a",
        kind: "reject_kyc",
        note: "Deed photo is a screenshot of an old listing. Rejected.",
        at: hours(80),
        actor: "Nour Fakhoury",
      },
    ],
  },
];

export const MOCK_ALERTS: ScamAlert[] = [
  {
    id: "al-01",
    pattern: "shared_ip",
    severity: "high",
    status: "open",
    createdAt: hours(6),
    title: "Three posters, one Hamra café IP",
    detail:
      "Karim, a new account, and a dormant handle all posted from 185.76.x in 40 minutes. Listings use stock kitchen photos.",
    signal: "IP 185.76.44.18 · 3 accounts · 40 min window",
    accounts: [
      {
        id: "u-01",
        firstName: "Karim",
        lastName: "Nassar",
        email: "karim.nassar@gmail.com",
        phone: "+961 3 441 220",
        accountStatus: "active",
        warningCount: 0,
      },
      {
        id: "u-16",
        firstName: "Tarek",
        lastName: "Haddad",
        email: "tarek.h.ads@gmail.com",
        phone: "+961 81 220 119",
        accountStatus: "active",
        warningCount: 0,
      },
      {
        id: "u-17",
        firstName: "Elie",
        lastName: "Mansour",
        email: "elie.m.rent@outlook.com",
        phone: "+961 70 118 442",
        accountStatus: "active",
        warningCount: 0,
      },
    ],
    listingIds: [],
    history: [],
  },
  {
    id: "al-02",
    pattern: "duplicate_phone",
    severity: "critical",
    status: "reviewing",
    createdAt: hours(22),
    title: "Same WhatsApp on four Achrafieh accounts",
    detail:
      "+961 70 228 441 is on Maya plus three throwaways created this week. Two already have live listings.",
    signal: "Phone +961 70 228 441 · 4 accounts",
    accounts: [
      {
        id: "u-04",
        firstName: "Maya",
        lastName: "Khoury",
        email: "maya.khoury@outlook.com",
        phone: "+961 70 228 441",
        accountStatus: "restricted",
        warningCount: 1,
      },
      {
        id: "u-18",
        firstName: "Sara",
        lastName: "K",
        email: "sara.k.rooms@gmail.com",
        phone: "+961 70 228 441",
        accountStatus: "active",
        warningCount: 1,
      },
      {
        id: "u-19",
        firstName: "M.",
        lastName: "Khoury",
        email: "mk.achrafieh@gmail.com",
        phone: "+961 70 228 441",
        accountStatus: "active",
        warningCount: 0,
      },
    ],
    listingIds: [],
    history: [
      {
        id: "ah-02a",
        kind: "warn",
        note: "Warned Maya; throwaways still live.",
        at: hours(40),
        actor: "Lina Haddad",
      },
      {
        id: "ah-02b",
        kind: "review",
        note: "Moved to review — waiting on phone ownership.",
        at: hours(20),
        actor: "Nour Fakhoury",
      },
    ],
  },
  {
    id: "al-03",
    pattern: "cloned_listings",
    severity: "critical",
    status: "open",
    createdAt: hours(3),
    title: "Rita’s Verdun studio cloned twice",
    detail:
      "Two new posters copied Rita’s photos, price, and copy with one-line edits. Original listing is still live.",
    signal: "Photo hash match 96% · 2 clones",
    accounts: [
      {
        id: "u-20",
        firstName: "Tony",
        lastName: "Abi",
        email: "tony.abi.rent@gmail.com",
        phone: "+961 3 118 770",
        accountStatus: "active",
        warningCount: 0,
      },
      {
        id: "u-21",
        firstName: "Lara",
        lastName: "M",
        email: "lara.m.studio@hotmail.com",
        phone: "+961 71 990 221",
        accountStatus: "active",
        warningCount: 0,
      },
    ],
    listingIds: ["l-02"],
    history: [],
  },
  {
    id: "al-04",
    pattern: "rapid_signup",
    severity: "watch",
    status: "open",
    createdAt: hours(11),
    title: "Burst of student-looking Gmail signups",
    detail:
      "Nine accounts in 12 minutes from the same /24, all with empty profiles and no campus domain. Likely a farm, not AUB students.",
    signal: "9 signups · 12 min · AS42020",
    accounts: [
      {
        id: "u-22",
        firstName: "User",
        lastName: "8821",
        email: "user8821.tmp@gmail.com",
        phone: "+961 81 000 221",
        accountStatus: "active",
        warningCount: 0,
      },
      {
        id: "u-23",
        firstName: "User",
        lastName: "8822",
        email: "user8822.tmp@gmail.com",
        phone: "+961 81 000 222",
        accountStatus: "active",
        warningCount: 0,
      },
    ],
    listingIds: [],
    history: [],
  },
];

export const MOCK_DOMAINS: AcademicDomain[] = [
  {
    id: "dom-01",
    domain: "mail.aub.edu",
    institution: "AUB",
    studentCount: 412,
  },
  {
    id: "dom-02",
    domain: "lau.edu.lb",
    institution: "LAU",
    studentCount: 287,
  },
  {
    id: "dom-03",
    domain: "usj.edu.lb",
    institution: "USJ",
    studentCount: 198,
  },
  {
    id: "dom-04",
    domain: "ndu.edu.lb",
    institution: "NDU",
    studentCount: 64,
  },
  {
    id: "dom-05",
    domain: "usek.edu.lb",
    institution: "USEK",
    studentCount: 41,
  },
];
