import { slugify, type AdminGovernorate, type AdminNeighborhood, type ZoneOrigin } from "./types";

function area(
  id: string,
  districtId: string,
  name: string,
  listingCount: number,
  origin: ZoneOrigin = "official",
): AdminNeighborhood {
  return {
    id,
    districtId,
    name,
    slug: slugify(name),
    origin,
    listingCount,
  };
}

export const MOCK_ZONES: AdminGovernorate[] = [
  {
    id: "gov-beirut",
    name: "Beirut",
    slug: "beirut",
    arabicName: "بيروت",
    districts: [
      {
        id: "dist-beirut",
        governorateId: "gov-beirut",
        name: "Beirut",
        slug: "beirut",
        origin: "official",
        neighborhoods: [
          area("n-achrafieh", "dist-beirut", "Achrafieh", 48),
          area("n-mar-mikhael", "dist-beirut", "Mar Mikhael", 31),
          area("n-gemmayzeh", "dist-beirut", "Gemmayzeh", 22),
          area("n-hamra", "dist-beirut", "Hamra", 41),
          area("n-ras-beirut", "dist-beirut", "Ras Beirut", 18),
          area("n-verdun", "dist-beirut", "Verdun", 15),
          area("n-jnah", "dist-beirut", "Jnah", 9),
          area("n-badaro", "dist-beirut", "Badaro", 14),
          area("n-ain-mreisseh", "dist-beirut", "Ain El Mreisseh", 7),
          area("n-saifi", "dist-beirut", "Saifi Village", 4, "custom"),
        ],
      },
    ],
  },
  {
    id: "gov-ml",
    name: "Mount Lebanon",
    slug: "mount-lebanon",
    arabicName: "جبل لبنان",
    districts: [
      {
        id: "dist-matn",
        governorateId: "gov-ml",
        name: "Matn",
        slug: "matn",
        origin: "official",
        neighborhoods: [
          area("n-broummana", "dist-matn", "Broummana", 12),
          area("n-dbayeh", "dist-matn", "Dbayeh", 19),
          area("n-antelias", "dist-matn", "Antelias", 16),
          area("n-jdeideh", "dist-matn", "Jdeideh", 11),
          area("n-sin-el-fil", "dist-matn", "Sin El Fil", 8),
          area("n-mansourieh", "dist-matn", "Mansourieh Heights", 3, "custom"),
        ],
      },
      {
        id: "dist-keserwan",
        governorateId: "gov-ml",
        name: "Keserwan",
        slug: "keserwan",
        origin: "official",
        neighborhoods: [
          area("n-jounieh", "dist-keserwan", "Jounieh", 27),
          area("n-kaslik", "dist-keserwan", "Kaslik", 9),
          area("n-zouk", "dist-keserwan", "Zouk Mosbeh", 6),
          area("n-adma", "dist-keserwan", "Adma", 5),
        ],
      },
      {
        id: "dist-jbeil",
        governorateId: "gov-ml",
        name: "Jbeil",
        slug: "jbeil",
        origin: "official",
        neighborhoods: [
          area("n-byblos", "dist-jbeil", "Byblos", 14),
          area("n-amchit", "dist-jbeil", "Amchit", 4),
          area("n-halat", "dist-jbeil", "Halat", 2),
        ],
      },
      {
        id: "dist-baabda",
        governorateId: "gov-ml",
        name: "Baabda",
        slug: "baabda",
        origin: "official",
        neighborhoods: [
          area("n-baabda", "dist-baabda", "Baabda", 7),
          area("n-hadath", "dist-baabda", "Hadath", 10),
          area("n-furn", "dist-baabda", "Furn El Chebbak", 5),
        ],
      },
      {
        id: "dist-aley",
        governorateId: "gov-ml",
        name: "Aley",
        slug: "aley",
        origin: "official",
        neighborhoods: [
          area("n-aley", "dist-aley", "Aley", 6),
          area("n-bhamdoun", "dist-aley", "Bhamdoun", 3),
        ],
      },
      {
        id: "dist-chouf",
        governorateId: "gov-ml",
        name: "Chouf",
        slug: "chouf",
        origin: "official",
        neighborhoods: [
          area("n-deir", "dist-chouf", "Deir El Qamar", 2),
          area("n-damour", "dist-chouf", "Damour", 3),
        ],
      },
    ],
  },
  {
    id: "gov-north",
    name: "North",
    slug: "north",
    arabicName: "الشمال",
    districts: [
      {
        id: "dist-tripoli",
        governorateId: "gov-north",
        name: "Tripoli",
        slug: "tripoli",
        origin: "official",
        neighborhoods: [
          area("n-tripoli", "dist-tripoli", "Tripoli", 21),
          area("n-mina", "dist-tripoli", "Mina", 6),
          area("n-qobbeh", "dist-tripoli", "Qobbeh", 3),
        ],
      },
      {
        id: "dist-koura",
        governorateId: "gov-north",
        name: "Koura",
        slug: "koura",
        origin: "official",
        neighborhoods: [
          area("n-amioun", "dist-koura", "Amioun", 4),
          area("n-anfeh", "dist-koura", "Anfeh", 3),
        ],
      },
      {
        id: "dist-batroun",
        governorateId: "gov-north",
        name: "Batroun",
        slug: "batroun",
        origin: "official",
        neighborhoods: [
          area("n-batroun", "dist-batroun", "Batroun", 8),
          area("n-chekka", "dist-batroun", "Chekka", 2),
        ],
      },
      {
        id: "dist-zgharta",
        governorateId: "gov-north",
        name: "Zgharta",
        slug: "zgharta",
        origin: "official",
        neighborhoods: [area("n-zgharta", "dist-zgharta", "Zgharta", 3)],
      },
    ],
  },
  {
    id: "gov-akkar",
    name: "Akkar",
    slug: "akkar",
    arabicName: "عكار",
    districts: [
      {
        id: "dist-akkar",
        governorateId: "gov-akkar",
        name: "Akkar",
        slug: "akkar",
        origin: "official",
        neighborhoods: [
          area("n-halba", "dist-akkar", "Halba", 4),
          area("n-qobayat", "dist-akkar", "Qobayat", 2),
        ],
      },
    ],
  },
  {
    id: "gov-south",
    name: "South",
    slug: "south",
    arabicName: "الجنوب",
    districts: [
      {
        id: "dist-sidon",
        governorateId: "gov-south",
        name: "Sidon",
        slug: "sidon",
        origin: "official",
        neighborhoods: [
          area("n-saida", "dist-sidon", "Saida", 17),
          area("n-ghaziyeh", "dist-sidon", "Ghaziyeh", 3),
        ],
      },
      {
        id: "dist-tyre",
        governorateId: "gov-south",
        name: "Tyre",
        slug: "tyre",
        origin: "official",
        neighborhoods: [area("n-tyre", "dist-tyre", "Tyre", 9)],
      },
      {
        id: "dist-jezzine",
        governorateId: "gov-south",
        name: "Jezzine",
        slug: "jezzine",
        origin: "official",
        neighborhoods: [area("n-jezzine", "dist-jezzine", "Jezzine", 2)],
      },
    ],
  },
  {
    id: "gov-nabatieh",
    name: "Nabatieh",
    slug: "nabatieh",
    arabicName: "النبطية",
    districts: [
      {
        id: "dist-nabatieh",
        governorateId: "gov-nabatieh",
        name: "Nabatieh",
        slug: "nabatieh",
        origin: "official",
        neighborhoods: [area("n-nabatieh", "dist-nabatieh", "Nabatieh", 5)],
      },
      {
        id: "dist-bint-jbeil",
        governorateId: "gov-nabatieh",
        name: "Bint Jbeil",
        slug: "bint-jbeil",
        origin: "official",
        neighborhoods: [area("n-bint-jbeil", "dist-bint-jbeil", "Bint Jbeil", 1)],
      },
    ],
  },
  {
    id: "gov-beqaa",
    name: "Beqaa",
    slug: "beqaa",
    arabicName: "البقاع",
    districts: [
      {
        id: "dist-zahle",
        governorateId: "gov-beqaa",
        name: "Zahle",
        slug: "zahle",
        origin: "official",
        neighborhoods: [
          area("n-zahle", "dist-zahle", "Zahle", 13),
          area("n-chtaura", "dist-zahle", "Chtaura", 4),
        ],
      },
      {
        id: "dist-west-beqaa",
        governorateId: "gov-beqaa",
        name: "West Beqaa",
        slug: "west-beqaa",
        origin: "official",
        neighborhoods: [area("n-jeb-jannine", "dist-west-beqaa", "Jeb Jannine", 2)],
      },
    ],
  },
  {
    id: "gov-bh",
    name: "Baalbek-Hermel",
    slug: "baalbek-hermel",
    arabicName: "بعلبك الهرمل",
    districts: [
      {
        id: "dist-baalbek",
        governorateId: "gov-bh",
        name: "Baalbek",
        slug: "baalbek",
        origin: "official",
        neighborhoods: [area("n-baalbek", "dist-baalbek", "Baalbek", 6)],
      },
      {
        id: "dist-hermel",
        governorateId: "gov-bh",
        name: "Hermel",
        slug: "hermel",
        origin: "official",
        neighborhoods: [area("n-hermel", "dist-hermel", "Hermel", 1)],
      },
    ],
  },
];
